wix/stylable

site/docs/guides/components-basics.md
`.root::btnLabel` should be `.formBtn::btnLabel`
=> Fix components-basics.md example

site/docs/getting-started.md, site/index.md
Please read thru it all.
Not sure if the install section is correct. To Do task for me: create a separate more detailed doc for install & configure. 
Should we link from "Getting Started" to 'index' page w/ detailed "story of Stylable"?
=> Rewrote Getting Started & index file

site/docs/getting-started.md, site/docs/getting-started/cheatsheet.md, site/docs/getting-started/install-configure.md, site/docs/getting-started/react-integration.md, site/index.md
Minor English edits plus fixes to links, commas, typos, code of st.css, etc.
=> Fixes to getting started section & index

site/_data/docs_nav.yml, site/_includes/header.html, site/docs/get-started.md
Adding Getting Started and 2 ref docs to TOC
Had to change name of Getting Started file (so not same as folder)
Changed name of first section to Discover (Getting Started - Getting Started didn't work). Used Discover cuz includes GS, installation (soon configuration), cheatsheet.
=> Added GS & missing files to TOC & fixed capitals

site/README.md, site/_data/docs_nav.yml, site/css/main.css, site/docs/getting-started/cheatsheet.md, site/docs/getting-started/react-integration.md, site/docs/guides/components-basics.md, site/docs/guides/stylable-component-library.md, site/docs/references/compose-css-class.md, site/docs/references/custom-selectors.md, site/docs/references/root.md, site/docs/welcome.md, site/index.md
Fixes to all broken links
Added Project Commons to TOC
Fixed font of subitem in TOC (main CSS)
Fixed readme instructions for running Jekyll
=> Fixes to links & TOC

site/docs/guides/components-basics.md
made sure you can copy-paste example code into Avi's project, and it would work.
=> changed example codes based on example project

site/docs/get-started.md, site/docs/getting-started/cheatsheet.md, site/docs/getting-started/install-configure.md, site/docs/getting-started/stylable-intelligence.md, site/docs/welcome.md
Merging all changes - Stylable Intelligence & Install fixes.
=> Minor fixes to install, getting started, stylable intelligence

site/docs/getting-started/react-integration.md
Just noticed this whilst browsing your docs.✨
=> Fix typo in React Integration Docs

site/_data/docs_nav.yml, site/docs/getting-started/react-integration.md, site/docs/getting-started/stylable-intelligence.md, site/docs/guides/runtime.md, src/runtime.ts, src/types.ts, tests/runtime.spec.ts
#201 this needs a change in the docs also
=> change stylesheet function behavior

src/index.ts, src/types.ts, tsconfig.json
mixin types (sssh.... they're all strings)
=> adding types for mixins, removing noUnusedLocals

tests/diagnostics.spec.ts, tests/functions.spec.ts, tests/utils/diagnostics.ts
moved functions diagnostics to functions spec file
=> extracted diagnostics testing mechanism

site/_data/docs_nav.yml, site/docs/getting-started/cheatsheet.md, site/docs/references/extending-through-js.md, site/docs/references/formatters.md, site/docs/references/imports.md, site/docs/references/mixins.md
TOC wasn't highlighting entry until removed "syntax" from file name. Now it works.
=> Changed title of mixin-syntax to mixins cuz of problem w/ TOC

src/types.ts, tests/utils/stylable-dom-util.spec.ts, tests/utils/stylable-dom-util.ts
=> Added matcher for style state

package.json, src/pseudo-states.ts, src/stylable-transformer.ts, tests/diagnostics.spec.ts, yarn.lock
=> fix wraning on vendor prefixed pseudos fixes #244

src/stylable-utils.ts, tests/stylable-transformer/mixins.spec.ts
improve animation and @keyframes handling in mixins
=> mixin keyframes

src/stylable-transformer.ts, tests/stylable-transformer/scoping-edge-cases.spec.ts
* Reset meta to originMeta beteewn selectors
* Pass originMeta to scope root
=> fixes #302

packages/stylable-webpack-plugin/src/StylableBootstrapModule.js, packages/stylable-webpack-plugin/src/StylableWebpackPlugin.js, packages/stylable-webpack-plugin/test/e2e/helpers/project-runner.js, packages/stylable-webpack-plugin/test/unit/stylable-webpack-plugin.unit.spec.js
* Remove entryReplacment concept
* Inject bootstrap at the mainTemplate startup
* Added default config for production mode
=> Default Production mode config + Remove entryReplacement

package.json, packages/stylable-scripts/package.json, packages/stylable/src/bundle.ts, packages/stylable/src/optimizer/stylable-optimizer.ts, packages/stylable/src/pseudo-states.ts, packages/stylable/src/state-validators.ts, packages/stylable/src/stylable-assets.ts, packages/stylable/src/stylable-mixins.ts, packages/stylable/src/stylable-processor.ts, packages/stylable/src/stylable-resolver.ts, packages/stylable/src/stylable-utils.ts, packages/stylable/src/stylable-value-parsers.ts, packages/stylable/tests/diagnostics.spec.ts, packages/stylable/tests/functions.spec.ts, packages/stylable/tests/matchers/results.ts, packages/stylable/tests/mixins/css-mixins.spec.ts, packages/stylable/tests/mixins/js-mixins.spec.ts, packages/stylable/tests/mixins/mixins.spec.ts, packages/stylable/tests/pseudo-states.spec.ts, packages/stylable/tests/stylable-ast-mixin.spec.ts, packages/stylable/tests/stylable-optimizer.spec.ts, packages/stylable/tests/stylable-processor.spec.ts, packages/stylable/tests/stylable-transformer/post-process-and-hooks.spec.ts, packages/stylable/tests/utils/diagnostics.ts, packages/stylable/tests/utils/generate-test-util.ts, packages/stylable/tsconfig.json, yarn.lock
removed unused locals from stylable core
=> removed unused

package.json, packages/stylable-webpack-plugin/test/e2e/autoprefixer-project.spec.ts, packages/stylable-webpack-plugin/test/e2e/projects/autoprefixer-project/src/index.js, packages/stylable-webpack-plugin/test/e2e/projects/autoprefixer-project/src/index.st.css, packages/stylable-webpack-plugin/test/e2e/projects/autoprefixer-project/webpack.config.js, yarn.lock
=> webpack-plugin: Add a sample project using postcss autoprefixer plugin

packages/cli/package.json, packages/core/package.json, packages/dom-test-kit/package.json, packages/e2e-test-kit/package.json, packages/jest/package.json, packages/node/package.json, packages/react-scripts/package.json, packages/runtime/package.json, packages/stylable.io/package.json, packages/webpack-extensions/package.json, packages/webpack-plugin/package.json
=> Add repository url to all package.json files

packages/stylable.io/docs/getting-started/react-integration.md, packages/stylable.io/docs/getting-started/stylable-intelligence.md, packages/stylable.io/docs/guides/components-basics.md, packages/stylable.io/docs/references/custom-selectors.md, packages/stylable.io/docs/references/mixins.md, packages/stylable.io/docs/references/pseudo-classes.md
I fixed some documentation files
=> fixed some errors in the documentation

packages/core/src/selector-utils.ts, packages/core/src/stylable-meta.ts, packages/core/src/stylable-processor.ts, packages/core/src/stylable-transformer.ts, packages/core/src/stylable-value-parsers.ts, packages/core/tests/diagnostics.spec.ts, packages/core/tests/pseudo-states.spec.ts, packages/core/tests/scope-directive.spec.ts, packages/core/tests/utils/diagnostics.ts, packages/e2e-test-kit/src/mem-fs.ts, packages/stylable.io/_data/docs_nav.yml, packages/stylable.io/docs/references/st-scope.md
Add a new syntax feature to Stylable - `@st-scope`.
As referenced in issues #411 #445 #450.
Further information will be included in the readme to come.
=> [WIP] @st-scope

packages/webpack-plugin/src/PluginOptions.js, packages/webpack-plugin/src/StylableDependencies.js, packages/webpack-plugin/src/StylableParser.js, packages/webpack-plugin/src/StylableWebpackPlugin.js, packages/webpack-plugin/test/e2e/dynamic-bug.spec.ts, packages/webpack-plugin/test/e2e/projects/dynamic-bug/node_modules/test-components/badge.js, packages/webpack-plugin/test/e2e/projects/dynamic-bug/node_modules/test-components/badge.st.css, packages/webpack-plugin/test/e2e/projects/dynamic-bug/node_modules/test-components/package.json, packages/webpack-plugin/test/e2e/projects/dynamic-bug/node_modules/test-components/text.js, packages/webpack-plugin/test/e2e/projects/dynamic-bug/node_modules/test-components/text.st.css, packages/webpack-plugin/test/e2e/projects/dynamic-bug/src/index-a.js, packages/webpack-plugin/test/e2e/projects/dynamic-bug/src/index-b.js, packages/webpack-plugin/test/e2e/projects/dynamic-bug/webpack.config.js
* Add weak deps in parser
* Add options to override resolveNamespace
=> StylableWebpackPlugin:

packages/runtime/package.json, packages/webpack-plugin/src/PluginOptions.js, packages/webpack-plugin/src/StylableWebpackPlugin.js, packages/webpack-plugin/src/StyleableAutoInitDependency.js, packages/webpack-plugin/src/getModuleInGraph.js, packages/webpack-plugin/test/e2e/projects/split-chunks-2/node_modules/lib/index.js, packages/webpack-plugin/test/e2e/projects/split-chunks-2/node_modules/lib/index.st.css, packages/webpack-plugin/test/e2e/projects/split-chunks-2/node_modules/lib/package.json, packages/webpack-plugin/test/e2e/projects/split-chunks-2/node_modules/lib/test.js, packages/webpack-plugin/test/e2e/projects/split-chunks-2/node_modules/lib/test.st.css, packages/webpack-plugin/test/e2e/projects/split-chunks-2/src/index.js, packages/webpack-plugin/test/e2e/projects/split-chunks-2/src/index.st.css, packages/webpack-plugin/test/e2e/projects/split-chunks-2/webpack.config.js, packages/webpack-plugin/test/e2e/split-chunks-2.spec.ts
* Add new way to inject runtime at entry module
=> New entry inject

packages/stylable.io/docs/getting-started/react-integration.md, packages/stylable.io/docs/guides/components-basics.md, packages/stylable.io/docs/guides/runtime.md, packages/stylable.io/docs/references/class-selectors.md, packages/stylable.io/docs/references/css-vars.md, packages/stylable.io/docs/references/extend-stylesheet.md, packages/stylable.io/docs/references/extending-through-js.md, packages/stylable.io/docs/references/mixins.md, packages/stylable.io/docs/references/namespace.md, packages/stylable.io/docs/references/pseudo-classes.md, packages/stylable.io/docs/references/root.md, packages/stylable.io/docs/references/st-scope.md, packages/stylable.io/docs/references/state-parameter-types.md, packages/stylable.io/docs/references/tag-selectors.md
Updated all stylable.io docs to reflect new v2 APIs.
=> Update docs for v2

package.json, packages/optimizer/package.json, packages/optimizer/src/stylable-optimizer.ts, packages/webpack-plugin/test/e2e/optimizations.spec.ts, yarn.lock
Replacing minifier due to bugs in the now unmaintained (-ish) CleanCSS.
=> Replace current CSS minifier (CleanCSS) with CSSO

packages/core/src/stylable-processor.ts, packages/core/test/diagnostics.spec.ts
=> fix warn of classes inside @stScope

packages/cli/src/build.ts, packages/cli/src/cli.ts, packages/cli/src/generate-manifest.ts, packages/cli/test/cli.spec.ts, packages/module-utils/src/module-source.ts, packages/webpack-plugin/src/plugin-options.ts, packages/webpack-plugin/src/stylable-webpack-plugin.ts, packages/webpack-plugin/src/types.ts, packages/webpack-plugin/test/e2e/3rd-party-standalone.spec.ts, packages/webpack-plugin/test/e2e/projects/3rd-party-standalone/node_modules/test-components/button.js, packages/webpack-plugin/test/e2e/projects/3rd-party-standalone/node_modules/test-components/button.st.css, packages/webpack-plugin/test/e2e/projects/3rd-party-standalone/node_modules/test-components/button.st.css.js, packages/webpack-plugin/test/e2e/projects/3rd-party-standalone/node_modules/test-components/index.js, packages/webpack-plugin/test/e2e/projects/3rd-party-standalone/node_modules/test-components/index.st.css, packages/webpack-plugin/test/e2e/projects/3rd-party-standalone/node_modules/test-components/index.st.css.js, packages/webpack-plugin/test/e2e/projects/3rd-party-standalone/node_modules/test-components/package.json, packages/webpack-plugin/test/e2e/projects/3rd-party-standalone/src/index.js, packages/webpack-plugin/test/e2e/projects/3rd-party-standalone/src/index.st.css, packages/webpack-plugin/test/e2e/projects/3rd-party-standalone/webpack.config.js
* Add default export to cli output in compat mode
* Add basic build manifest generation
=> Fix cli compat output

packages/core/src/custom-values.ts, packages/core/src/functions.ts, packages/core/src/native-reserved-lists.ts, packages/core/src/stylable-value-parsers.ts, packages/core/test/functions.spec.ts, packages/webpack-plugin/src/stylable-generator.ts
- add native `slotted` pseudo-element, and `constant`, `env` and `local` functions
- perserve `format` function quotation
- improve `value()` diagnostics to better account for `custom-values`
=> Declaration value processing improvements and native parts update

packages/core/src/native-reserved-lists.ts
Bringing the `v1` branch inline with the `master` branch.
=> Update reserved native lists - functions, pseudo clases and pseudo elements

package.json, packages/core/package.json, packages/core/src/custom-values.ts, packages/core/src/functions.ts, packages/core/src/pseudo-states.ts, packages/core/src/stylable-processor.ts, packages/core/src/stylable-transformer.ts, packages/core/src/stylable-value-parsers.ts, packages/core/test/arguement-parser.spec.ts, packages/core/test/stylable-transformer/value.spec.ts, packages/language-service/package.json, packages/language-service/src/lib/completion-providers.ts, packages/language-service/src/lib/feature/pseudo-class.ts, packages/language-service/src/lib/provider.ts, packages/language-service/src/lib/types.ts, yarn.lock
cleanup various places using untyped require() calls
=> fix(types): use postcss-value-parser types

packages/cli/src/cli.ts, packages/cli/test/cli.spec.ts
- also add test to prevent regression
=> CLI: Pass through "useNamespaceReference" parameter

.travis.yml
=> infra: Travis tests on Node 14

packages/optimizer/src/namespace-optimizer.ts
=> Use generated namespace as unique identifier in optimizing cache keys

package.json, packages/cli/src/cli.ts, packages/cli/test/cli.spec.ts, yarn.lock
migrated cli entry to typed yargs experience and added `.strict()`
=> feat: stc fails when given unknown flags

packages/jest/src/jest.ts
=> Jest: added core path and version to Jest integration caching key

packages/webpack-plugin/README.md, packages/webpack-plugin/src/plugin-options.ts, packages/webpack-plugin/src/stylable-generator.ts, packages/webpack-plugin/src/types.ts, packages/webpack-plugin/test/e2e/errors-project.spec.ts, packages/webpack-plugin/test/e2e/projects/errors-project/src/index.js, packages/webpack-plugin/test/e2e/projects/errors-project/src/index.st.css, packages/webpack-plugin/test/e2e/projects/errors-project/webpack.config.js
This PR open the option to emit stylable errors as webpack error and break the bundle process.
=> add option to emit errors for error diagnostics

packages/module-utils/src/module-source.ts
=> refactor: format output js a bit nicer

packages/core/src/stylable-mixins.ts, packages/core/test/mixins/partial-css-mixins.spec.ts
* Fix dependent vars inclusions 
* Fix nested mixins of partial mixins
=> -st-partial-mixin fixes

packages/webpack-extensions/src/stylable-forcestates-plugin.ts, packages/webpack-extensions/test/unit/forcestates-plugin-plugins.spec.ts
allow extending force states plugin to support native classes as states.
=> Add plugin capabilities to force-states

packages/stylable.io/docs/references/class-selectors.md, packages/stylable.io/docs/references/custom-selectors.md, packages/stylable.io/docs/references/extend-stylesheet.md, packages/stylable.io/docs/references/formatters.md, packages/stylable.io/docs/references/global-selectors.md, packages/stylable.io/docs/references/imports.md, packages/stylable.io/docs/references/mixins.md, packages/stylable.io/docs/references/namespace.md, packages/stylable.io/docs/references/pseudo-classes.md, packages/stylable.io/docs/references/pseudo-elements.md, packages/stylable.io/docs/references/root.md, packages/stylable.io/docs/references/tag-selectors.md, packages/stylable.io/docs/references/variables.md
Remove some unneeded comments and add missing namespacing where missing.
=> Minor documentation fixes

packages/optimizer/test/ast-optimizations.spec.ts, packages/optimizer/test/stylable-optimizer.spec.ts, packages/runtime/src/index.ts, packages/runtime/test/unit/css-runtime-renderer.spec.ts, packages/runtime/test/unit/css-runtime-stylesheet.spec.ts, packages/runtime/test/unit/keyed-list-renderer.spec.ts, packages/webpack-extensions/test/e2e/metadata-loader-case.spec.ts, packages/webpack-extensions/test/e2e/projects/manifest-plugin/fs-manifest.spec.ts, packages/webpack-extensions/test/e2e/projects/manifest-plugin/manifest.spec.ts
for compatibility with upcoming project references
=> refactor(test): use package names in imports

tsconfig.base.json
improves cold build time from 90s -> 60s on my machine.
=> perf(build): explicit typings loading

package.json, packages/language-service/package.json, webpack-config-browser/webpack.config.base.js, yarn.lock
- adjust webpack remapping to be simpler now
- regenerate lock file
=> chore(deps): file-services@5.3.1

packages/core/src/stylable-processor.ts, packages/core/test/diagnostics.spec.ts
=> feat(core): warn on invalid custom property rename

packages/create-stylable-app/template/ts-react-webpack/.eslintrc, packages/create-stylable-app/template/ts-react-webpack/src/app.tsx, packages/create-stylable-app/template/ts-react-webpack/src/header.tsx, packages/create-stylable-app/template/ts-react-webpack/tsconfig.json, tsconfig.base.json
- https://reactjs.org/blog/2020/09/22/introducing-the-new-jsx-transform.html
- also turn on "noUncheckedIndexedAccess" by default.
=> feat(template): use React's modern jsx transform; noUncheckedIndexedAccess

packages/eslint-plugin-stylable/src/stylable-es-lint.ts
fix(eslint-plugin-stylable): performance regression
=> Fix performance regression in lint process

packages/core/src/functions.ts, packages/core/src/stylable-value-parsers.ts
Nothing fancy: 
1. Removed one level of if nesting 
2. Only process arguments then there is a JS formatter
3. Only trim value if need to report error
4. Fix typo
=> refactor(core): improve functions transform code

packages/rollup-plugin/package.json, packages/rollup-plugin/src/index.ts, packages/rollup-plugin/test/projects/simple-stylable/index.st.css, packages/rollup-plugin/test/projects/simple-stylable/js-function.js, packages/rollup-plugin/test/rollup-plugin-stylable.spec.ts
Add support for importing JS files inside Stylable files
=> feat(rollup-plugin): add js import support

packages/runtime/src/runtime.ts, packages/runtime/src/types.ts
Add a missing `undefined` as a possible state value.
=> Fix states runtime typings

packages/webpack-plugin/src/mini-css-support.ts, typings/externals/index.d.ts
Solve issue with future version of mini-css-extract-plugin
=> fix(webpack-plugin): mini-css-extract-plugin CSSModule build

packages/cli/src/base-generator.ts, packages/cli/test/fixtures/test-generator.ts, packages/cli/test/generate-index.spec.ts
=> feat(cli): allow generateReExports to filter files from index generation

packages/cli/src/build.ts, packages/cli/test/cli-watch.spec.ts, packages/core/test/stylable-resolver.spec.ts
=> fix(cli): watch did not copy changed assets referenced by Stylable files

packages/core/src/stylable-processor.ts, packages/core/test/stylable-transformer/at-property.spec.ts
=> fix: property definition override conflicting imported symbol

packages/core-test-kit/README.md, packages/core-test-kit/src/matchers/results.ts, packages/experimental-loader/README.md
=> docs(core-test-kit): add missing mixin from example

packages/core/src/stylable-transformer.ts, packages/core/test/pseudo-states.spec.ts, packages/core/test/stylable-transformer/scoping.spec.ts
=> fix(core):  scope selectors inside a functional pseudo-class correctly

packages/cli/package.json, packages/cli/src/cli.ts, packages/cli/test/cli.spec.ts, packages/create-stylable-app/package.json, yarn.lock
new yargs version changed the way "implies" works if targetted option has a default value
=> fix(cli): compatibility with yargs@7.1.0

package.json, yarn.lock
upgrade to jsdom@17.0.0 and regenerate lock file
=> chore(deps-dev): jsdom@17.0.0

packages/core/src/stylable-mixins.ts, packages/core/src/stylable-processor.ts, packages/core/src/stylable-value-parsers.ts, packages/core/test/diagnostics.spec.ts, packages/core/test/mixins/js-mixins.spec.ts, packages/core/test/stylable-value-parsers.spec.ts
=> fix(core@3.x): js mixin re export

packages/cli/README.md, packages/cli/src/cli-codemod.ts, packages/cli/src/code-mods/apply-code-mods.ts, packages/cli/src/code-mods/code-mods.ts, packages/cli/src/code-mods/load-codemods.ts, packages/cli/src/code-mods/st-global-custom-property-to-at-property.ts, packages/cli/src/code-mods/st-import-to-at-import.ts, packages/cli/src/code-mods/types.ts, packages/cli/src/index.ts, packages/cli/test/cli-codemod.spec.ts, packages/cli/test/codemods/st-import-to-at-import.spec.ts
Allow to specify external code mods by request
Rework on the cli flow
Also fix issue with multiple `;` in st-import-to-at-import code mod
=> feat(cli): codemod API improvements

packages/webpack-extensions/src/create-metadata-stylesheet.ts, packages/webpack-extensions/src/stylable-manifest-plugin.ts, packages/webpack-extensions/src/stylable-metadata-loader.ts, packages/webpack-extensions/src/types.ts, packages/webpack-extensions/test/e2e/manifest.css-vars.spec.ts, packages/webpack-extensions/test/e2e/projects/manifest-plugin/Button.comp.st.css, packages/webpack-extensions/test/e2e/projects/manifest-plugin/webpack.css-vars.config.js
Port manifest cssVars exports to v3
=> feat(webpack-extensions): add ability to generate named exports in manifest index (3.x)

.mocharc.js
Lately, we get timeouts now and then from "heavy" tests from machines with limited resources, this PR should fix it.
=> infra: limit the number of jobs in the test runner

packages/core/src/types.ts, packages/optimizer/src/stylable-optimizer.ts, packages/webpack-plugin/src/plugin.ts
This should improve type compatibility in edge case where you pin Stylable versions.
reason #2178
=> fix: use IStylableOptimizer in webpack config

packages/jest/src/index.ts
This PR is also support jest 26
=> fix(jest): export createTransformer named for interop

packages/code-formatter/src/formatter.ts, packages/code-formatter/test/formatter.spec.ts
=> fix(code-formatter): grid formatting was breaking the css

package-lock.json, packages/cli/package.json
We should have dependencies validation.
=> fix(cli): missing dependencies

packages/jest/README.md
Add text about how to ignore Stylable files from existing css integrations
=> Update Jest README.md

packages/cli/src/messages.ts, packages/cli/src/watch-handler.ts
Another attempt to find the flakiness source
=> feat(cli): log when stop watching

packages/core/src/features/st-import.ts, packages/core/src/stylable.ts, packages/core/test/features/st-import.spec.ts
This PR exposes an API to the analyzed stylable imports of a stylesheet
=> feat(core): import analyze API

packages/cli/src/code-mods/apply-code-mods.ts, packages/cli/test/cli-codemod.spec.ts
Allow retrive the filePath from inside the code mod
=> fix: added filePath to postcss parse

packages/runtime/src/inject-styles.ts
=> fix: js runtime explode in edge case with involving multiple builds

packages/create-stylable-app/template/ts-react-webpack-lean/webpack.config.js, packages/create-stylable-app/template/ts-react-webpack/webpack.config.js
add extensions for common font formats
=> feat(create-st-app): support font assets

packages/core/src/features/css-custom-property.ts, packages/core/test/features/css-custom-property.spec.ts
Transform `@property st-global(--name)` correctly
fix: #2722
=> fix: transform global `@property`

packages/core-test-kit/test/inline-expectations.spec.ts, packages/core/src/features/st-import.ts, packages/core/src/stylable-resolver.ts, packages/core/test/features/st-import.spec.ts
propagate the resolve module error to the diagnostic.
=> feat: expand resolution error with error details

packages/core-test-kit/src/inline-expectation.ts, packages/core-test-kit/test/inline-expectations.spec.ts
This PR add a diagnostic dump of all the diagnostics found on stylesheet meta in case a diagnostic is expected and not matched at all (no match for `message>location>severity`). 
The diagnostic dump is logged only once for multiple inline expectations in case one or more fail to match a diagnostic
=> feat(core-test-kit): log diagnostics dump on diagnostic match fail

packages/language-service/test/lib-new/ast-from-position.spec.ts
Refactor standalone expectation to a helper to make the expectation clearer to understand and write
=> infra: unified expectation to improve read/write

packages/webpack-plugin/src/plugin-utils.ts, packages/webpack-plugin/test/e2e/projects/native-css/src/external.css, packages/webpack-plugin/test/e2e/projects/native-css/webpack.config.js
This PR fixes an unhandled error when adding a css file as entry to webpack
=> fix(webpack): unhandled native css external entry

.github/workflows/next.yml, .github/workflows/npm.yml, .github/workflows/publish-tag.yml, .github/workflows/release3.yml, .github/workflows/tests.yml
https://github.com/actions/checkout/releases/tag/v4.0.0
=> ci: use actions/checkout@v4

packages/core-test-kit/src/test-stylable-core.ts, packages/core-test-kit/test/test-stylable-core.spec.ts
This PR making the test kit much easier to work with, sheets are auto-completed from keys or entries.
=> refactor: 10x better types for test kit.

packages/esbuild/src/stylable-esbuild-plugin.ts, packages/esbuild/test/e2e/esbuild-testkit.ts, packages/esbuild/test/e2e/rebuild/rebuild.spec.ts
in watch mode when there was transform error stylable esbuild plugin did not recover well this PR fixes that.
=> fix: esbuild plugin break after stylable error

.github/workflows/next.yml, .github/workflows/npm.yml, .github/workflows/publish-tag.yml
https://github.com/wixplosives/pleb/releases/tag/v7.0.0
=> ci: use pleb@7

.github/workflows/npm.yml
=> ci: use Node 20 for publishing

.github/dependabot.yml, .github/workflows/next.yml, .github/workflows/npm.yml, .github/workflows/publish-tag.yml, .github/workflows/tests.yml, package-lock.json, package.json, packages/build-tools/package.json, packages/cli/package.json, packages/code-formatter/package.json, packages/core-test-kit/package.json, packages/core/package.json, packages/create-stylable-app/package.json, packages/custom-value/package.json, packages/dom-test-kit/package.json, packages/e2e-test-kit/package.json, packages/esbuild/package.json, packages/jest/package.json, packages/language-service/package.json, packages/module-utils/package.json, packages/node/package.json, packages/optimizer/package.json, packages/rollup-plugin/package.json, packages/runtime/package.json, packages/schema-extract/package.json, packages/uni-driver/package.json, packages/webpack-extensions/package.json, packages/webpack-plugin/package.json
https://nodejs.org/en/blog/release/v22.11.0
=> infra!: support Node 22 (LTS); drop 18

package-lock.json, package.json, packages/webpack-plugin/src/plugin-utils.ts
new version requires adjustments to asset handling.
https://github.com/webpack/webpack/releases/tag/v5.96.1
https://github.com/webpack/webpack/releases/tag/v5.96.0
=> chore(deps): webpack@5.96.1
