wix/stylable

site/docs/references/class-selectors.md
site/docs/references/compose-css-class.md
site/docs/references/extend-stylesheet.md
site/docs/references/global-selectors.md
site/docs/references/imports.md
site/docs/references/mixin-syntax.md
site/docs/references/namespace.md
site/docs/references/pseudo-classes.md
site/docs/references/pseudo-elements.md
site/docs/references/root.md
site/docs/references/tag-selectors.md
site/docs/references/theme.md
site/docs/references/variables.md

Reference Docs:
Added /* CSS */ and "/* CSS output */ to code examples that didn't have css file names
Added /* React integration */ where relevant
Plus misc fixes to note style and headings

Removed css headings & added to code

---

matchers.d.ts
runtime.d.ts
src/bundle.ts
src/generator.ts
src/index.ts
src/parser.ts
src/runtime.ts
src/stylable-processor.ts
src/stylable-transformer.ts
src/types.ts
src/value-template.ts
tests/utils/generate-test-util.ts

Allows referencing a type in a .d.ts file without needing to use import. Furthermore, it allows us to configure a TypeScript project so that we have separate *.st.css and *.css module types, while providing RuntimeStylesheet type for imported '.st.css'. :)

Create global namespace Stylable for types

---

src/native-pseudos.ts

List of pseudo-elements had the list of classes, and vice versa. 
Fixed to issue correct diagnostics.

swapped lists of pseudo elements and classes

---

src/index.ts
src/pseudo-states.ts
src/state-validators.ts
tests/pseudo-states.spec.ts

- also added tests for unknown state types
- support explicit boolean state definition, e.g.
`-st-states: myState(boolean);`

changed string regex validator api to match other validators

---

packages/stylable/src/selector-utils.ts
packages/stylable/src/stylable-processor.ts
packages/stylable/src/stylable-transformer.ts
packages/stylable/tests/diagnostics.spec.ts
packages/stylable/tests/pseudo-states.spec.ts
packages/stylable/tests/utils/diagnostics.ts

Very basic example can be seen here - for a more thorough review see tests use case.
Should warn:
```css
:import {
-st-from: "./blah.st.css";
-st-named: blah;
}
.blah {}
```
```css
button {}
```
Should not warn:
```css
:import {
-st-from: "./blah.st.css";
-st-named: blah;
}
.root {}
.root .blah {}
```
```css
.root button {}
```

Add diagnostics for unscoped elements and imported classes

---

packages/stylable/src/stylable-utils.ts
packages/stylable/src/stylable-value-parsers.ts
packages/stylable/tests/diagnostics.spec.ts

Trying to use a CSS mixin without a named parameter will now issue a warning:
```css
:vars {
myColor: red;
}
.mixed {
color: value(myColor);
}
.someClass {
-st-mixin: mixed(666);
}
```
Warning: `CSS mixins must use named parameters (e.g. "func(name value, [name value, ...])")`
Correct example:
```css
...
.someClass {
-st-mixin: mixed(myColor 666);
}
```

Core: Add warning for CSS mixin without named params

---

packages/stylable/src/pseudo-states.ts
packages/stylable/src/utils.ts
packages/stylable/tests/pseudo-states.spec.ts

Core: fix bug with double wrapped (with quotes) state parameters

---

packages/stylable/src/stylable-processor.ts
packages/stylable/tests/diagnostics.spec.ts

Previously, warnings about lower case default imports from component stylesheets would warn about the entire import rule (see issue #357).
Now, they target the `-st-default` declaration specifically, leading to more precise warnings in the stylable-intelligence extension.

Core: lowercase default imports now warn about the correct node

---

packages/stylable-jest/test/jest.spec.ts
packages/stylable-node/src/stylable-module-source.ts
packages/stylable-node/test/require-hook.spec.ts
packages/stylable-scripts/template/src/globals.d.ts

`stylable-scripts` global `.d.ts` definitions now import their definitions from  `stylable-runtime`.
Also correct `stylable-node` exported stylesheet type to `default`.

Centralize scripts global types usage 

---

packages/stylable/src/pseudo-states.ts
packages/stylable/tests/pseudo-states.spec.ts

Adding this error in preparation of support for native CSS variables.
This error is intended to prevent people from using native syntax for their state names.

Report error when defining states beginning with "--"

---

README.md
packages/cli/README.md
packages/cli/package.json
packages/core/README.md
packages/core/tests/utils/test-utils.ts
packages/dom-test-kit/LICENSE
packages/dom-test-kit/README.md
packages/dom-test-kit/package.json
packages/dom-test-kit/src/index.ts
packages/dom-test-kit/src/stylable-dom-util.ts
packages/dom-test-kit/tests/stylable-dom-util.spec.ts
packages/dom-test-kit/tsconfig.json
packages/dom-test-kit/tslint.json
packages/dom-test-kit/webpack.config.js
packages/e2e-test-kit/README.md
packages/e2e-test-kit/package.json
packages/jest/README.md
packages/jest/package.json
packages/node/README.md
packages/node/package.json
packages/react-scripts/README.md
packages/react-scripts/package.json
packages/runtime/README.md
packages/runtime/package.json
packages/webpack-extensions/package.json
packages/webpack-plugin/README.md

Exposes `StylableDOMUtil` used for Stylable related DOM testing
- DOM selection / targetting 
- Stylable selector transformation/scoping
- Custom state resolvers

dom-test-kit: extract package from core testing utils

---

packages/webpack-extensions/package.json
packages/webpack-extensions/src/stylable-html-snapshot.ts
packages/webpack-plugin/src/stylable-module-helpers.js

Add the ability for users of the `HTMLSnapshot Plugin` to customize which component logic file associated with a specific stylesheet.

Added a 'getLogicModule' option to the snapshot plugin

---

packages/node/src/stylable-module-source.ts
packages/node/test/require-hook.spec.ts

Module interop of typescript and babel looks for the '__esModule' field on exports to determine whether the original source was esm

Node: correct require hook not marking generated modules as esm

---

packages/jest/package.json
packages/jest/src/jest.ts

allows @stylable/jest to be used as part of a globally installed CLI

@stylable/jest: ensure generated module uses own copy of runtime

---

packages/webpack-plugin/src/StylableWebpackPlugin.js
packages/webpack-plugin/test/e2e/unsafe-mute-diagnostics.spec.ts

Lowering the severity of this error so that it will not break the build process. Graceful behavior should remain, despite increased bundle size.

"duplicate module namespace" severity change from error to warning

---

packages/core/src/optimizer/classname-optimizer.ts
packages/core/src/optimizer/stylable-optimizer.ts
packages/core/src/stylable-meta.ts
packages/core/src/stylable-transformer.ts
packages/core/tests/stylable-transformer/global.spec.ts
packages/webpack-plugin/test/e2e/optimizations.spec.ts
packages/webpack-plugin/test/e2e/projects/optimizations/src/index.js
packages/webpack-plugin/test/e2e/projects/optimizations/src/index.st.css

Behavior after fixing the bug:
```css
/* entry.st.css */
.root {}          // optimized
.part {}          // optimized
:global(.a) {}    // not optimized
:global(.b .c) {} // not optimized
```

Fix bug causing global classes to be optimized in production mode

---

packages/core/src/native-reserved-lists.ts

Fixes warning for native css paint() property.
Resolves #561.

Added 'paint()' property to native-reserved-lists

---

packages/webpack-plugin/src/stylable-webpack-plugin.ts
packages/webpack-plugin/src/types.ts

Adds missing second parameter for additional plugin integration into `@stylable/webpack-plugin`. This was caused by a mistake during the conversion of the project to TypeScript.

fix webpack plugins api

---

.gitignore
packages/jest/package.json
packages/jest/src/index-legacy.ts
packages/jest/src/jest.ts
packages/module-utils/src/module-factory.ts
packages/module-utils/test/index.spec.ts
packages/module-utils/test/test-kit.ts
packages/node/src/require-hook.ts
packages/runtime/package.json
packages/runtime/scripts/build-runtime.ts
packages/runtime/scripts/ts-lib-bundler.ts
packages/runtime/src/css-runtime-stylesheet-legacy.ts
packages/runtime/src/index-legacy.ts
packages/runtime/test/e2e/projects/runtime-legacy/src/index.js
packages/runtime/test/e2e/projects/runtime-legacy/src/index.st.css
packages/runtime/test/e2e/projects/runtime-legacy/webpack.config.js
packages/runtime/test/e2e/runtime-legacy.spec.ts
packages/runtime/test/unit/css-runtime-stylesheet-legacy.spec.ts
packages/webpack-plugin/src/plugin-options.ts
packages/webpack-plugin/src/runtime-dependencies.ts
packages/webpack-plugin/src/stylable-webpack-plugin.ts
packages/webpack-plugin/src/types.ts

Set to `false` by default, can be switched on with the `legacyRuntime` flag set to `true`.
When active, the default import on `*.st.css` files is available and maintains the old API, with the new output (states as classes), while still passing through any `data-*` attributes.
Supported packages:
* jest
* node
* module-utils
* webpack-plugin
* runtime

Add Legacy runtime API support

---

packages/core/src/functions.ts
packages/core/test/stylable-transformer/value.spec.ts

Should resolve a known variable even in unknown formatter functions.
You will still get a warning about an unknown formatter function being used.
Example:
```css
:vars {
param: green;
}
.container {
color: unknownFunc(value(param)); /* resolves to unknownFunc(green) */
}
```

Fix stylable variable resolution in an unknown formatter

---

packages/runtime/README.md
packages/runtime/test/unit/css-runtime-stylesheet-legacy.spec.ts
packages/schema-extract/src/index.ts
packages/schema-extract/src/main.ts
packages/schema-extract/src/types.ts
packages/schema-extract/test/test.spec.ts

- separate module and symbol typings
- add `namespace` and `moduleDependencies` to extracted module output
- include imports used as an alias in the outputted schema
- no longer include unused imported symbols in the schema
- add initial css vars support

Schema Extract: fixes and additions

---

packages/optimizer/src/stylable-optimizer.ts

It breaks production mode by making classes disappear.

Disable minifier restructuring in optimizer

---

packages/core/package.json
packages/core/src/cssdocs.ts
packages/core/src/index.ts
packages/core/src/stylable-meta.ts
packages/core/src/stylable-processor.ts
packages/core/src/stylable-transformer.ts
packages/core/test/comments-metadata.spec.ts
packages/core/test/cssdocs.spec.ts
packages/schema-extract/src/main.ts
packages/schema-extract/src/types.ts
packages/schema-extract/test/cssdocs.spec.ts
packages/schema-extract/test/mock-namespace.ts
packages/schema-extract/test/test.spec.ts
yarn.lock

Expose a utility method in `@stylable/core` called `getCssDocsForSymbol`, that accepts a `StylableSymbol` (`class` or `element` for the moment), and attempts to extract the docBlock written above the symbol node.
These cssDocs are automatically added to the output from `@stylable/schema-extract`.

[core, schema-extract] Add cssDocs support

---

packages/module-utils/src/module-factory.ts
packages/module-utils/test/index.spec.ts

This add to the backward compatibility module export default key (like in v1)

export default from legacy

---

packages/cli/README.md
packages/cli/cli.js
packages/cli/package.json
packages/cli/src/cli.ts
packages/cli/test/cli.spec.ts
packages/cli/test/fixtures/test-require-hook.js

This will allow to pass the CLI `@ts-tools` require hook handler to run typescript (mixins, custom values, etc) from source.

Add flag to CLI accepting require hooks to run

---

packages/core/src/stylable-value-parsers.ts
packages/core/test/stylable-value-parsers.spec.ts

This tackles the same issue as PR #724, just in a slightly different way.
The example below will no longer throw an exception:
```css
Button(color red, size 2px,)
```

Handle trailing commas in named arguments

---

packages/jest/src/jest.ts

so that if the runtime location is changed locally, the module will be re-created.
fixes #875

jest: specify cache key method

---

packages/core/src/stylable-transformer.ts
packages/core/test/custom-selectors.spec.ts
packages/core/test/intellisense/intellisense.spec.ts
packages/core/test/stylable-transformer/scoping.spec.ts

- fix a bug concerning scoping nested pseudo state elements
- change scoping mechanism to use a `class` based context
Future: 
- sort out issues with custom-selectors, see #890
- add future test case for resolveSelectorElements, see #891

Fix a bug concerning scoping nested pseudo state elements

---

packages/core/src/stylable-resolver.ts
packages/core/src/stylable-transformer.ts
packages/core/src/stylable-utils.ts
packages/core/test/stylable-resolver.spec.ts
packages/core/test/stylable-transformer/exports.spec.ts

- fix edge case with local extended classes and exports
- fix resolving a class as local and not an alias when extended
- add protection against a case causing an infinite loop in the resolver

Local extended class export bug and resolver improvements

---

packages/core/src/stylable-processor.ts
packages/core/src/stylable-utils.ts
packages/core/test/diagnostics.spec.ts
packages/core/test/functions.spec.ts
packages/core/test/stylable-resolver.spec.ts
packages/core/test/stylable-transformer/post-process-and-hooks.spec.ts
yarn.lock

This follows a fix in the latest version of [postcss](https://github.com/postcss/postcss/releases/tag/7.0.25)

Remove handling for incorrect path resolution in cross-os situations

---

packages/language-service/src/lib/css-service.ts
packages/language-service/src/lib/diagnosis.ts
packages/language-service/src/lib/feature/color-provider.ts
packages/language-service/src/lib/service.ts
packages/language-service/test-kit/completions-asserters.ts
packages/language-service/test/fixtures/server-cases/st-scope/directive.st.css
packages/language-service/test/fixtures/server-cases/st-scope/inside-value-local-vars.st.css
packages/language-service/test/fixtures/server-cases/st-scope/local-class-from-selector.st.css
packages/language-service/test/fixtures/server-cases/st-scope/local-vars.st.css
packages/language-service/test/fixtures/server-cases/st-scope/selector.st.css
packages/language-service/test/fixtures/server-cases/st-scope/single-variable-color.st.css
packages/language-service/test/lib/colors.spec.ts
packages/language-service/test/lib/completions/st-scope.spec.ts
packages/language-service/test/lib/diagnostics.spec.ts
packages/language-service/test/lib/references.spec.ts

- Stylable and native CSS completions
- Native CSS diagnostics
- Native CSS color info (vscode color squares) and presentation (editing color picker) 
- Using a Stylable value in a media query parameter no longer issues a warning or break css completions

@st-scope and CSS service quality of life improvements

---

packages/core/src/create-infra-structure.ts
packages/core/src/index.ts
packages/core/src/module-resolver.ts
packages/core/src/stylable.ts
packages/core/src/types.ts
packages/e2e-test-kit/src/project-runner.ts
packages/webpack-plugin/src/stylable-webpack-plugin.ts
packages/webpack-plugin/test/e2e/projects/tsconfig-resolver-plugin/node_modules/test-components/button.js
packages/webpack-plugin/test/e2e/projects/tsconfig-resolver-plugin/node_modules/test-components/button.st.css
packages/webpack-plugin/test/e2e/projects/tsconfig-resolver-plugin/node_modules/test-components/index.js
packages/webpack-plugin/test/e2e/projects/tsconfig-resolver-plugin/node_modules/test-components/index.st.css
packages/webpack-plugin/test/e2e/projects/tsconfig-resolver-plugin/node_modules/test-components/package.json
packages/webpack-plugin/test/e2e/projects/tsconfig-resolver-plugin/src/index.js
packages/webpack-plugin/test/e2e/projects/tsconfig-resolver-plugin/src/index.st.css
packages/webpack-plugin/test/e2e/projects/tsconfig-resolver-plugin/webpack.config.js
packages/webpack-plugin/test/e2e/tsconfig-resolver-plugin.spec.ts

- not just options for `enhanced-resolve`.
- `webpack-plugin` uses it to create the default resolver with the wrapped `inputFileSystem`.
- fixes 3rd party resolution when `tsconfig-paths-webpack-plugin` is used, as it requires `readJson`.

core: allow consumers to specify module resolver

---

packages/core-test-kit/src/generate-test-util.ts
packages/core/src/cached-process-file.ts
packages/core/src/create-infra-structure.ts
packages/core/src/memory-minimal-fs.ts
packages/core/test/cached-process-file.spec.ts
packages/core/test/stylable-ast-mixin.spec.ts
packages/core/test/stylable-resolver.spec.ts

- exposes a `readlinkSync` function which always throws.
- allows using Stylable with minimal-fs without turning off symlinks especially in the tests.
- refactored file/directory lookup implementation. supports absolute paths properly. does not resolve relative-paths.

core: adjust minimal-fs for enhanced-resolve

---

packages/dom-test-kit/src/stylable-dom-util.ts
packages/dom-test-kit/test/contract-test.ts

Resolves #1031.
This solution will remove the invalid syntax that is being output by returning the original composing class.
We still need to enhance the variety of selectors we support in our `dom-test-kit` to support complex selectors, custom elements, pseudo-states and more.

dom-test-kit: add handling for scoping a class selector that includes composition

---

packages/webpack-plugin/package.json

```
[18:43:26][npm run test] Error: Cannot find module 'webpack/lib/MultiModule'
[18:43:26][npm run test]     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
[18:43:26][npm run test]     at Function.Module._load (internal/modules/cjs/loader.js:507:25)
[18:43:26][npm run test]     at Function._load (/home/builduser/agent00/work/f0c170388923639/promote-seo/promote-seo/node_modules/@sentry/node/dist/integrations/console.js:41:47)
[18:43:26][npm run test]     at Module.require (internal/modules/cjs/loader.js:637:17)
[18:43:26][npm run test]     at require (internal/modules/cjs/helpers.js:22:18)
[18:43:26][npm run test]     at Object.<anonymous> (/home/builduser/agent00/work/f0c170388923639/promote-seo/promote-seo/node_modules/@stylable/webpack-plugin/src/StylableWeb …
```

Webpack@5 breaks expectations

---

packages/dom-test-kit/test/contract-test.ts
packages/language-service/package.json
packages/language-service/src/lib/css-service.ts
packages/language-service/src/lib/feature/color-provider.ts
packages/language-service/src/lib/service.ts
packages/language-service/test-kit/asserters.ts
packages/language-service/test-kit/completions-asserters.ts
yarn.lock

- use new `textdocument` package
- use named imports from vscode CSS service to use less dependencies
- narrow `onDefinition` return type

Improve LSP for external integrations

---

packages/core/src/stylable-processor.ts
packages/core/test/stylable-processor.spec.ts

Fixed issue where using absolute paths in stylable imports causes resolution bug

Core: fix absolute path .st.css imports

---

packages/stylable.io/docs/guides/migration-v3.md

This PR adds a short migration guide to hopefully help those upgrading from stylable 1 to to stylable 2/3
it is quite specific to React but imo is much better than having nothing.

docs(migration-v3): add doc with some notes about migrating to v3

---

packages/core/src/cached-process-file.ts
packages/language-service/src/lib/feature/color-provider.ts
packages/language-service/src/lib/service.ts
packages/language-service/test-kit/asserters.ts
packages/language-service/test-kit/stylable-fixtures-lsp.ts
packages/language-service/test/fixtures/server-cases/colors/imported-color.st.css
packages/language-service/test/fixtures/server-cases/colors/substring-var-import.st.css
packages/language-service/test/lib/colors.spec.ts
packages/language-service/test/lib/diagnostics.spec.ts

Currently, color presentation calls on `value(<some variable>)` do nothing. From now on, color presentation will edit the entire `value()` string inline - not the source variable.
Furthermore, the color square previews will no longer appear in the `:import` `named` field, and only where colors are used.
```css
/* before color presentation on "value(aColor) */
:vars {
aColor: red;
}
.root {
color: value(aColor);
}
```
```css
/* after color presentation on "value(aColor) */
:vars {
aColor: red;
}
.root {
color: rgba(12, 34, 56, 0.75); /* value chosen in colorpicker  */
}
```

Language Service: ColorPresentation edits "value(x)" colors inline

---

packages/e2e-test-kit/src/project-runner.ts
packages/webpack-plugin/src/plugin-options.ts
packages/webpack-plugin/src/stylable-webpack-plugin.ts
packages/webpack-plugin/src/types.ts
packages/webpack-plugin/test/e2e/dynamic-split-chunks.spec.ts
packages/webpack-plugin/test/e2e/dynamic-split-chunks.ts
packages/webpack-plugin/test/e2e/projects/dynamic-split-chunks/src/compA/compA.js
packages/webpack-plugin/test/e2e/projects/dynamic-split-chunks/src/compA/compA.st.css
packages/webpack-plugin/test/e2e/projects/dynamic-split-chunks/src/compB/compB.js
packages/webpack-plugin/test/e2e/projects/dynamic-split-chunks/src/compB/compB.st.css
packages/webpack-plugin/test/e2e/projects/dynamic-split-chunks/src/index.js
packages/webpack-plugin/test/e2e/projects/dynamic-split-chunks/webpack.config.js

This fixes a bug that cause our plugin to emit dynamic chunks css when we extract css into one bundle.
* Change the 3 EOL between css asset in the bundle to 1
* Fix emit of redundant css assets
This should be a patch but added the ability to disable this behavior if needed via 
`skipDynamicCSSEmit: false`

Fix dynamic emit of assets when includeDynamicModulesInCSS is true

---

packages/core/src/stylable-value-parsers.ts
packages/core/test/mixins/css-mixins.spec.ts

When using mixins and formatters as arguments the formatter arguments turned in to nulls
```css
.root {
-st-mixin: Mixin(param formatter(a, b, c))
}
```
the results was
```css
.root {
color: anullbnullc;
}
```

fix issue with mixins and formatters as arguments

---

packages/core/src/timed-cache.ts

the first test in `timed-cache.spec.ts` depends on Date.now() being 1ms exact.
allow it to clean if diff from last call === timeout (which is also correct), hoping this would fix the flakiness.

fix: timed cache without timer flakiness

---

packages/webpack-extensions/src/stylable-metadata-plugin.ts

We want to break the build process if component.json in metadata plugin is invalid

Add error when component json is invalid

---

packages/core/package.json
packages/core/src/stylable-assets.ts
yarn.lock

`url-regex` has a security vulnerability.
`is-url-superb` uses native `URL` api to verify text is a valid url. much cleaner.
ref:
https://github.com/advisories/GHSA-v4rh-8p82-6h5w
https://github.com/kevva/url-regex/issues/70

security: replace url-regex with is-url-superb

---

packages/core-test-kit/src/generate-test-util.ts
packages/core/src/create-infra-structure.ts

now uses the actual resolver the implementation uses during units

core-test-kit: refactor to use createInfra

---

packages/jest/src/jest.ts

Include the `@stylable/runtime` version as part of the `@stylable/jest` caching key. A different runtime version should cause new transformations and not yield previously cached results.

Jest: add runtime version to jest cache key

---

packages/experimental-loader/README.md
packages/experimental-loader/src/create-runtime-target-code.ts
packages/experimental-loader/src/stylable-runtime-loader.ts
packages/experimental-loader/src/stylable-transform-loader.ts
packages/experimental-loader/test/exports-only-mode.spec.ts
packages/experimental-loader/test/projects/exports-only-mode/index.js
packages/experimental-loader/test/projects/exports-only-mode/index.st.css
packages/experimental-loader/test/projects/exports-only-mode/webpack.config.ts

Allow SSR builds to not extract css and get only the runtime stylesheet exported

Experimental-loader: add exportsOnly mode for transform loader

---

packages/webpack-plugin/src/hash-content-util.ts
packages/webpack-plugin/src/stylable-webpack-plugin.ts
packages/webpack-plugin/test/e2e/projects/simplest-project-content-hash/src/index.js
packages/webpack-plugin/test/e2e/projects/simplest-project-content-hash/src/index.st.css
packages/webpack-plugin/test/e2e/projects/simplest-project-content-hash/webpack.config.js
packages/webpack-plugin/test/e2e/simplest-project-content-hash.spec.ts

Add support to webpack plugin to allow filename output path config to include `[contenthash]`

Add support for content hash in webpack css output

---

packages/e2e-test-kit/src/project-runner.ts
packages/experimental-loader/README.md
packages/experimental-loader/src/stylable-transform-loader.ts
packages/experimental-loader/test/errors-integration.spec.ts
packages/experimental-loader/test/projects/errors-integration/index.js
packages/experimental-loader/test/projects/errors-integration/index.st.css
packages/experimental-loader/test/projects/errors-integration/webpack.config.ts

`experimental-loader` now emits webpack errors and warnings from Stylable diagnostics.
Add option to always emit errors even for warnings by settings `alwaysEmitErrors: true`

Experimental loader emit diagnostics as webpack errors and warnings

---

packages/eslint-plugin-stylable/src/stylable-es-lint.ts
packages/eslint-plugin-stylable/tests/stylable-es-lint.spec.ts

fix `classes[x]` lint error. as we can't know the end value.

Fix lint error on computed member identifier

---

packages/e2e-test-kit/src/project-runner.ts
packages/webpack-extensions/src/index.ts
packages/webpack-extensions/src/stylable-manifest-plugin.ts
packages/webpack-extensions/src/stylable-metadata-loader.ts
packages/webpack-extensions/src/types.ts
packages/webpack-extensions/test/e2e/projects/manifest-plugin/fs-manifest.spec.ts
packages/webpack-extensions/test/e2e/projects/manifest-plugin/manifest.spec.ts
packages/webpack-extensions/test/e2e/projects/manifest-plugin/webpack.config.ts
packages/webpack-extensions/test/e2e/projects/manifest-plugin/webpack.fs-manifest.config.ts

* Allow the manifest plugin to output fs metadata.
* Export StylableManifestPlugin from index

Add support for metadata format from manifest plugin

---

packages/webpack-extensions/src/stylable-manifest-plugin.ts
packages/webpack-extensions/test/e2e/projects/manifest-plugin/fs-manifest.spec.ts

Our integration points dose not handle well other file types in the fs object. so we only emit st.css files

Remove package.json from fs-manifest

---

package.json
packages/experimental-loader/package.json
packages/experimental-loader/src/stylable-transform-loader.ts
packages/experimental-loader/src/warning.ts
yarn.lock

This might be a breaking changes since it requires minimum webpack version 4.27.0
closes #1282

Update Experimental loader to use css-loader v4

---

packages/core/src/state-validators.ts
packages/core/test/pseudo-states.spec.ts

The state validators: min, max, minLength and maxLength - are not inclusive.
When defining a `min(0)` validator and using `controlButtonAmount(0)` we get:
`expected "0" to be larger than or equal to 0" as seen in the picture.
Same goes for the other three validators.
This PR fixes that issue.

Fix numerical state validators

---

packages/core/test/mixins/js-mixins.spec.ts
packages/webpack-extensions/src/stylable-forcestates-plugin.ts
packages/webpack-extensions/test/unit/forcestates-plugin.spec.ts

* Allow force-states-plugin to use function for namespace mapping
* Export useful regexp for state name matching
* Add test for js fallback decl support

Allow force state plugin to use function for namespace mapping 

---

packages/webpack-extensions/src/create-forcestate-matchers.ts
packages/webpack-extensions/src/stylable-forcestates-plugin.ts
packages/webpack-extensions/test/unit/forcestates-plugin.spec.ts

* Add a util function for creating force states matchers.
This will allow editors in conjunction with the `force-states-plugin` to force css states on a DOM tree.

Add Util to create force state DOM matchers

---

packages/eslint-plugin-stylable/package.json
packages/eslint-plugin-stylable/src/stylable-es-lint.ts
packages/eslint-plugin-stylable/tests/stylable-es-lint.spec.ts
packages/language-service/package.json
packages/language-service/src/lib/typescript-support.ts
packages/language-service/test-kit/asserters.ts
packages/language-service/test-kit/completions-asserters.ts
packages/language-service/test-kit/stylable-fixtures-lsp.ts
packages/language-service/test/lib/definitions.spec.ts
packages/language-service/test/lib/references.spec.ts

no reason for `eslint-plugin-stylable` to install @file-services/node. reduce tree.

refactor: use native node apis where possible

---

packages/webpack-plugin/src/stylable-webpack-plugin.ts

I failed to reproduce the scenario that cause webpack to split modules in a way that the original reason is not in the same chunks of imported stylable file.
This PR fixes that problem by never removing Stylable files that used in JavaScript imports

Fix Removing stylable modules that are used in JavaScript

---

packages/core/src/stylable.ts
packages/language-service/src/lib/diagnosis.ts

- also, make `namespaceResolver` public on `Stylable` instances

language-service: fix diagnosis to use the correct stylable processor instance

---

packages/core/src/functions.ts
packages/core/test/mixins/js-mixins.spec.ts
packages/stylable.io/docs/references/extending-through-js.md

Allow usage of imported JavaScript string values inside Stylable value() function.
```css 
:import {
-st-from: "../my-js-values.js";
-st-named: myValue;
}
.myClass {
color: value(myValue);
}
```

Allow using JavaScript string values as Stylable import

---

packages/core-test-kit/src/generate-test-util.ts
packages/core/src/create-infra-structure.ts
packages/core/src/stylable-processor.ts
packages/language-service/test/lib/diagnostics.spec.ts

In our tests we use global diagnostics that are shared across all files. 
When we updated our test infra we accidentally introduced this behavior to the core infrastructure.

core: fix regression that causing diagnostics to be shared across files

---

package.json
packages/create-stylable-app/package.json
packages/create-stylable-app/template/ts-react-webpack/.eslintrc
packages/create-stylable-app/template/ts-react-webpack/README.md
packages/create-stylable-app/template/ts-react-webpack/src/index.tsx
packages/create-stylable-app/template/ts-react-webpack/template.js
packages/create-stylable-app/template/ts-react-webpack/tsconfig.json
packages/create-stylable-app/template/ts-react-webpack/webpack.config.js
yarn.lock

- default to `"transpileOnly": true` in webpack. combined with tsconfig.json's `"importsNotUsedAsValues": "error"`, it gives a consistent transpilation experience that properly removes type-only imports, and ignores unused variable diagnostics. "typecheck" script is still there to catch type issues.
- add "test" script which runs "typecheck" and "lint".
- removed `eslint-plugin-jsx-a11y`. less deps and nicer experience to prototype quickly with. can always be added by those creating real production sites.
- ensure template is type-checked using its own `tsconfig.json` when repository is being tested.

create-stylable-app: improve developer experience

---

packages/core/src/stylable-utils.ts
packages/core/test/stylable-utils.spec.ts

Feature: Added utility `scopeCSSVar` which generates the scoped css variable name from local name

Added generateScopedVar for stylable-utils

---

packages/core/src/stylable-processor.ts
packages/core/test/css-vars.spec.ts

```css
@st-global-custom-property a, b; /* doesn't break */
```
```css
@st-global-custom-property a , b; /* breaks */
```
The solution there should still probably be replaced by a proper parser that can handle more than spacings. (e.g. comments)

core: fix bug where odd spacings in '@st-global-custom-property' would break

---

packages/webpack-extensions/src/component-metadata-builder.ts
packages/webpack-extensions/src/stylable-metadata-plugin.ts
packages/webpack-extensions/test/e2e/projects/metadata-plugin-project/webpack.config.ts

Allow consumers to modify the module file path before it is injected to the metadata.
This allows projects that use symlinks to resolve the module file path in dev mode.

webpack-extensions: add the ability to modify the resource path for the metadata fs output

---

packages/runtime/src/types.ts

for projects using the new noUncheckedIndexedAccess typescript flag, `classes.root` gets a type of `string | undefined`, forcing the user to use `!` in many cases.
this change relaxes the type-check of the first parameter, at least until we have .d.ts generation with watch mode.

fix(runtime): compat with noUncheckedIndexedAccess

---

packages/cli/src/cli.ts

- otherwise, consumers have to write `--diagnostics true`, and `--no-some-flag` doesn't work.
- gave types for all other options

fix(cli): ensure --diagnostics works as boolean flag

---

packages/core/src/stylable-resolver.ts
packages/webpack-plugin/test/e2e/projects/resolve-js-with-context/src/index.js
packages/webpack-plugin/test/e2e/projects/resolve-js-with-context/src/index.st.css
packages/webpack-plugin/test/e2e/projects/resolve-js-with-context/src/node_modules/test1/comp.st.css
packages/webpack-plugin/test/e2e/projects/resolve-js-with-context/src/node_modules/test1/node_modules/test-inner/index.js
packages/webpack-plugin/test/e2e/projects/resolve-js-with-context/src/node_modules/test1/node_modules/test-inner/package.json
packages/webpack-plugin/test/e2e/projects/resolve-js-with-context/src/node_modules/test1/package.json
packages/webpack-plugin/test/e2e/projects/resolve-js-with-context/webpack.config.js
packages/webpack-plugin/test/e2e/resolve-js-with-context.spec.ts

Bugfix - JavaScript imports from st.css file are now resolved correctly with context

fix(core): use correct context when resolving js mixins

---

packages/core-test-kit/README.md
packages/core-test-kit/src/generate-test-util.ts
packages/core-test-kit/src/match-rules.ts
packages/core/test/stylable-transformer/elements.spec.ts

When creating Stylable transform tests usually the ugly part was to find the right selector in the AST and match it.
`expect((results.outputAst!.nodes[0] as postcss.Rule).selector).to.equal('...')`
Now we can write the matching selector inside the css as "magic comment" before the tested selector and we must specify the number of assertions.
```js
expectTransformOutput(
{
entry: `/style.st.css`,
files: {
'/style.st.css': {
namespace: 'ns',
content: `
/* @expect .ns__root */
.root {}
`
},
},
1
);
```

feat(core-test-kit): Test helper for matching target selector inline

---

packages/core/src/stylable-processor.ts
packages/core/test/diagnostics.spec.ts

fix a false report on scoped elements when scoping happens after the element node
Example of false report:
`div.root{}`

fix(core): fix false report on scoped elements

---

packages/cli/src/cli.ts
packages/core/src/stylable-resolver.ts
packages/core/src/stylable-transformer.ts
packages/core/src/stylable.ts
packages/core/test/stylable-transformer/scoping.spec.ts
packages/experimental-loader/src/cached-stylable-factory.ts
packages/experimental-loader/src/stylable-transform-loader.ts
packages/webpack-extensions/src/stylable-manifest-plugin.ts
packages/webpack-plugin/src/stylable-webpack-plugin.ts

Add resolver cache for all imports. this is an opt in so there is no breaking change. 
The ability improve dramatically the performance of stylable transform

Add resolver cache for symbol resolution.

---

packages/cli/bin/stc.js
packages/cli/package.json
packages/cli/test/cli.spec.ts

- for a more common package structure.
- named entrypoint `stc.js`, per cli name.

refactor(cli): move cli entry to bin folder

---

packages/cli/test/tsconfig.json
packages/core/test/tsconfig.json
packages/custom-value/test/tsconfig.json
packages/dom-test-kit/test/tsconfig.json
packages/eslint-plugin-stylable/test/tsconfig.json
packages/experimental-loader/test/tsconfig.json
packages/jest/test/tsconfig.json
packages/language-service/test/tsconfig.json
packages/module-utils/test/tsconfig.json
packages/node/test/tsconfig.json
packages/optimizer/test/tsconfig.json
packages/runtime/test/tsconfig.json
packages/schema-extract/test/tsconfig.json
packages/uni-driver/test/tsconfig.json
packages/webpack-extensions/test/tsconfig.json
packages/webpack-plugin/test/tsconfig.json
tsconfig.base.json

build time is roughly the same on my machine, so I don't expect this improve build speed as much as I hoped it would.

infra: ensure only tests can access test globals

---

packages/core/src/create-infra-structure.ts

mid-solution that ensures all non-absolute requests are resolved using the resolver, while absolute ones are returned untouched.
this allows flows calling the resolvePath with absolute paths to stay fast, while providing full/correct resolution for any non-absolute requests.
this change also has the potential to improve caching/correctness in locations that used the returned result as cache key.

fix(core): always resolve non-absolute requests

---

packages/language-service/src/lib/css-service.ts
packages/language-service/test/lib/diagnostics.spec.ts

fix(langauge-service): ignore diagnostic for "@st-global-custom-propety"

---

packages/core/src/selector-utils.ts
packages/core/src/stylable-processor.ts
packages/core/test/diagnostics.spec.ts

This example will trigger a false scoping diagnostic for `.classNeedsScoping`.
```
:import {                  
-st-from: "./blah.st.css;
-st-named: classNeedsScoping;
}
.cls {
-st-states: someState;
}
.cls:not(:someState) .classNeedsScoping {}  
```

False scoping diagnostic on selector with ":not()"

---

packages/create-stylable-app/template/ts-react-webpack/template.js
packages/create-stylable-app/template/ts-react-webpack/webpack.config.js

- one less dependency to worry about
- added `@type` comment in template definition for auto completions and hover info.

refactor: use native assets in create-stylable-app

---

packages/e2e-test-kit/src/project-runner.ts
packages/webpack-plugin/src/plugin.ts
packages/webpack-plugin/test/e2e/projects/watched-project-error-recovery/package.json
packages/webpack-plugin/test/e2e/projects/watched-project-error-recovery/src/index.js
packages/webpack-plugin/test/e2e/projects/watched-project-error-recovery/src/index.st.css
packages/webpack-plugin/test/e2e/projects/watched-project-error-recovery/webpack.config.js
packages/webpack-plugin/test/e2e/watched-project-error-recovery.spec.ts
packages/webpack-plugin/test/e2e/watched-project.spec.ts

When using `cssInjection: 'css'` if the css is invalid we break webpack. this PR fixes that.

fix(webpack-plugin): fix crash in optimization step when css is broken

---

packages/language-service/src/lib/completion-providers.ts
packages/language-service/src/lib/completion-types.ts
packages/language-service/test/lib/completions/completion.spec.ts
packages/language-service/test/test-kit/completions-asserters.ts

also reorder completion asserters according to at-rule/rule/declaration

Language-service: add completion for @st-global-custom-property

---

packages/webpack-plugin/src/loader-utils.ts
packages/webpack-plugin/src/loader.ts
packages/webpack-plugin/src/runtime-inject.ts
packages/webpack-plugin/test/e2e/simplest-project-used-exports.spec.ts

Sine webpack can opt out of removing pure exports (like we use in the loader) in certain configurations, this PR moves all injection points in the JavaScript module to the `StylableRuntimeDependency` apply phase.
This allows better decision point for when to inject the shared runtime and also prepare the ground for optimizing `keyframes` and `vars` exports.
fix #1698

fix(webpack-plugin): inject all exports only when usedExports enabled in dev

---

packages/webpack-plugin/src/mini-css-support.ts
packages/webpack-plugin/src/plugin.ts
packages/webpack-plugin/test/e2e/mini-css-extract.spec.ts

This PR enables the mini-css support in the webpack plugin.

fix(webpack-plugin): enable mini-css-extract-plugin feature

---

packages/webpack-extensions/src/compile-as-entry.ts

`compile-as-entry` should not add !! to the entry request. we want loaders to affect entry also.

Remove !! from entry request

---

packages/webpack-plugin/src/plugin.ts
packages/webpack-plugin/test/e2e/multiple-chunks-split.spec.ts
packages/webpack-plugin/test/e2e/projects/multiple-chunks-split/webpack.config.js

Modules inside concatenated module were ignored in split by entry 
Moved the logic of getting the modules inside an entry to `afterOptimizeTree`

fix(webpack-plugin): modules inside concatenated module were ignored

---

packages/core/src/stylable-processor.ts
packages/core/test/stylable-processor.spec.ts

Since file paths can contains `=` the split is not correct.

Better handling namespace reference

---

packages/create-stylable-app/template/ts-react-webpack/typings/globals.d.ts
packages/runtime/README.md
packages/runtime/package.json
packages/runtime/stylesheet.d.ts

The new TS snippet: 
```ts
// globals.d.ts
declare module '*.st.css' {
export const defaultExport: never;
export * from '@stylable/runtime/stylesheet';
export default defaultExport;
}
```

Change .st.css module declaration to disallow stylesheet default exports

---

packages/core/src/stylable-processor.ts
packages/core/test/stylable-transformer/general.spec.ts

This fixes issue where `:import` is not hoisted and overrides a mapped symbol (alias) 
This will cause X to not be transpiled correctly 
```css
:import{ -st-from: '...'; -st-default: X }
X{}
:import{ -st-from: '...'; -st-default: X }
X{}
```
This is working as intended
```css
:import{ -st-from: '...'; -st-default: X }
:import{ -st-from: '...'; -st-default: X }
X{}
X{}
```
`@st-imports` does not suffer from this behavior because they are processed before all other rules

fix(core): bug import order can override a mapped symbol

---

packages/language-service/src/lib/service.ts
packages/language-service/test/lib/completions/st-import.spec.ts

Running formatting on the following example:
```css
.x {}
@st-import Comp from "./top-level.st.css";
.root {}
```
returned incorrectly:
```css
.x {}
@st-import ;
.root {}
```
This broke our import parsing and is generally bad.

Fix incorrect formatting for st-import causing values to disappear

---

packages/core-test-kit/package.json
packages/core-test-kit/src/index.ts
packages/core-test-kit/src/inline-expectation.ts
packages/core-test-kit/test/inline-expectations.spec.ts
packages/core-test-kit/test/tsconfig.json
packages/core/test/mixins/css-mixins.spec.ts
packages/core/test/stylable-transformer/scope-selector-v2.spec.ts
packages/core/test/stylable-transformer/scoping.spec.ts
tsconfig.json

This PR takes the concept for inline expectation tests from `scope-selector-vs.spec` and add some more features:
format:
```css
/**
* Test transformed stylesheets inline expectation comments
* rule checking (place just before rule)
*
* full options:
* @check(label)[5] .selector {decl: value}
*
* basic:
* @check .selector
*
* with declarations (will check full match and order):
* @check .selector {decl1: value; decl2: value}
*
* label for check:
* @check(label for test) .selector
*
* target generated rules (mixin):
* @check[4] .selector
*
* support multi line declarations:
* @check .selector {
*     decl1: value;
*     decl2: value;
* }
*
* support multi checks:
* @check .selector
* @check[1] .selector:hover
*
* support atrule params (anything between the @atrule and body or semicolon)
* …
```

Test inline expectation

---

package.json
packages/core/package.json
packages/core/src/replace-rule-selector.ts
packages/core/src/stylable-utils.ts
typings/externals/index.d.ts
yarn.lock

fixes #1799 
this change drops the last runtime dependency bringing postcss@7 with it.
instead, code was ported to typescript and inlined.

security(core): drop postcss-selector-matches

---

packages/core/src/selector-utils.ts
packages/core/src/stylable-utils.ts
packages/core/test/mixins/css-mixins.spec.ts
packages/core/test/mixins/js-mixins.spec.ts

feat(core): support css mixins with `@supports` - fix: #1810
fix(core): mixin root found inside nested rule - fix: #1811

Fix mixins issue with nested atrules 

---

packages/webpack-plugin/src/webpack-config-stylable-excludes.ts

Exclude handling of Stylable files targeted by loader issuer option. 
fix #1781

fix(webpack-plugin): exclude stylable from issuers

---

packages/create-stylable-app/template/ts-react-rollup/typings/globals.d.ts
packages/create-stylable-app/template/ts-react-webpack/typings/globals.d.ts
packages/runtime/README.md

Both in `create-stylable-app` templates and `runtime` readme file.
Related doc from `stylable.io` will be fixed in its repo.

Fix global type definition to set default export as unknown instead of never

---

packages/core/src/stylable-processor.ts
packages/core/test/stylable-processor.spec.ts

```css
.x {
.y{}
}
```
should emit error

add error when nesting rules

---

.github/workflows/tests.yml
package.json
packages/e2e-test-kit/src/project-runner.ts
packages/experimental-loader/test/two-components-dynamic-order-prod.spec.ts
packages/experimental-loader/test/two-components-dynamic-order.spec.ts
packages/webpack-extensions/test/e2e/manifest.spec.ts
packages/webpack-plugin/test/e2e/simplest-project.spec.ts

reduces test run itself (just `mocha`) from 65s to 18s locally.

test: enable parallel testing

---

.prettierignore
packages/create-stylable-app/template/ts-react-rollup/tsconfig.json
packages/create-stylable-app/template/ts-react-webpack/tsconfig.json

Until the `.d.ts` if fully integrated these strict rules are annoying.

feat: make stylable app templates less strict

---

packages/jest/src/index.ts
packages/jest/src/jest.ts

- new major imports transformer as default if `__esModule`.
- also, 4th parameter is not passed to `getCacheKey` anymore, so verify it exists before checking for `'instrument'`.

fix(jest): compatibility with jest@27

---

packages/runtime/src/runtime.ts

We might need to consider again to validate es5 compatibility of the runtime so we don't add these kind of mistakes.

fix: remove non es5 code from runtime stylesheet

---

.github/workflows/npm.yml
.github/workflows/release3.yml
.github/workflows/tests.yml

it uses the cache action under the hood, but actually caches npm/yarn's cache directory per platform.
hoping that this done right will cause ci to install faster.

infra(ci): enable cache in setup-node

---

packages/cli/src/base-generator.ts
packages/cli/test/fixtures/test-generator.ts
packages/cli/test/generate-index.spec.ts

This prevent overriding `generateFileIndexEntry` which leads to smaller footprint when writing custom generator.

feat(cli): allow generateReExports to filter files from index generation

---

packages/core/src/stylable-resolver.ts
packages/core/test/diagnostics.spec.ts
packages/core/test/stylable-resolver.spec.ts

This PR fixes `@st-import` resolution validation errors. 
We did not emitted warnings on them because we couldn't find the "correct declaration".

fix(core): emit validation diagnostics on @st-imports

---

packages/language-service/src/lib/feature/formatting.ts
packages/language-service/src/lib/service.ts
packages/language-service/test/test-kit/asserters.ts

API change due to the code formatter extraction was a bit harsh, restoring `getDocumentFormatting` on the main LSP service.

fix(language-service): limit api break to type fix

---

.gitignore
packages/core-test-kit/README.md
packages/core-test-kit/src/diagnostics.ts
packages/core-test-kit/src/generate-test-util.ts
packages/core-test-kit/src/match-rules.ts
packages/core/test/stylable-resolver.spec.ts
packages/core/test/stylable-transformer/elements.spec.ts
packages/optimizer/test/stylable-optimizer.spec.ts

We had too many ways to test. This PR reduce few of them.
I don't know any other package that is using `@stylable/core-test-kit` so I assume we can snick a patch here. (needs double check)

refactor(core-test-kit): reduce semi-duplicate APIs

---

packages/core/src/pseudo-states.ts
packages/core/test/pseudo-states.spec.ts
packages/dom-test-kit/src/stylable-dom-util.ts
packages/webpack-extensions/test/unit/forcestates-plugin.spec.ts

It turns out that we can avoid creating `[class~=...]` for custom states that have invalid class characters. 
Only spaces are really invalid and we always replace them with `_`, other characters are escaped by the `stringifySelector` function.
This might need more eyes to make sure we don't break anything.
This feature is related to #1870 and if we go for it resolve the optimization issue.

feat(core): don't transform custom states to attributes

---

packages/runtime/src/types.ts

Since the `root` class is always there, this PR should give the typescript user a nicer experience if he does not use st declaration files

feat(runtime): add root property to classes map type

---

packages/core/src/pseudo-states.ts
packages/core/test/pseudo-states.spec.ts

should warn when pseudo-class expects params but none was given
Closes #1936

fix(core): assure that pseudo-classes warn when no arguments are given

---

packages/language-service/src/lib/provider.ts
packages/language-service/test/fixtures/server-cases/definitions/imported-default.st.css
packages/language-service/test/fixtures/server-cases/definitions/imported-path.st.css
packages/language-service/test/fixtures/server-cases/definitions/st-imported-default.st.css
packages/language-service/test/fixtures/server-cases/definitions/st-imported-named-end.st.css
packages/language-service/test/fixtures/server-cases/definitions/st-imported-named-start.st.css
packages/language-service/test/fixtures/server-cases/definitions/st-imported-path.st.css
packages/language-service/test/lib/definitions.spec.ts

Go-to-definition with imports behavior should be much better:
- `from` paths are now clickable
- `default` imports work more consistently 
- `named` imports work more consistently
- prevent exceptions from being thrown in certain cases 
This is just an improvement, there are still plenty of quirks.
Fixes: 
- #1148

fix(language-service): improve definition support for both :import and @st-import

---

packages/webpack-plugin/README.md

[It's mentioned in the package.json](https://github.com/wix/stylable/blob/master/packages/webpack-plugin/package.json#L11) that webpack should be at least `5.30.0` version.
Updating the README

docs(webpack-plugin): sync min required webpack version in README with package.json

---

packages/create-stylable-app/src/cli-main.ts

`yarg` released a new minor version which contains a breaking change related to strict arguments parsing. this PR fixes this issue by demanding the project-name 
Note: we need a basic test for this package as well

fix(create-stylable-app): missing demand for project name

---

packages/core/src/stylable-meta.ts
packages/core/src/stylable-processor.ts
packages/core/src/stylable-transformer.ts
packages/core/src/stylable-value-parsers.ts
packages/core/src/utils.ts
packages/core/test/diagnostics.spec.ts
packages/core/test/stylable-processor.spec.ts
packages/core/test/stylable-transformer/global.spec.ts

We want to allow to expose and use global keyframes.
Importing global keyframes should be seamless and be resolve like other keyframes.
```css
@keyframes stGlobal(my-global-keyframes) {
from {}
to {}
}
```
Closes #1559

feat(core): support defining and using global keyframes

---

packages/cli/package.json

`@stylable/cli` is using `@stylable/module-utils` but did not declare it as a dependency in the `package.json`

fix(cli): add missing 'module-utils' dependency (v3)

---

packages/core/src/stylable-value-parsers.ts
packages/core/test/stylable-processor.spec.ts
packages/core/test/stylable-transformer/global.spec.ts

We were rethinking the naming of our st function (`stGlobal`, `stArray`, `stMap`) and we would like to stick with the native CSS naming conventions ([CSS Functional Notation
](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Functions)).
Syntax:
```css
selector {
property: functional-notation( [argument]? [, argument]! );
}
```

refactor: rename keyframes "stGlobal" function to "st-global"

---

packages/cli/src/code-mods/apply-code-mods.ts
packages/cli/src/code-mods/code-mods.ts
packages/cli/src/code-mods/st-import-to-at-import.ts
packages/cli/test/cli-codemod.spec.ts

This PR uses the diagnostics of stylable inside the code-mod.
Regardless it handles parsing errors that the code-mod did not handle before.

feat(cli): use stylable diagnostics in the code-mod CLI

---

packages/core/src/stylable.ts
packages/node/src/require-hook.ts

10x to @AviVahl we found that we are missing `resolverCache` in `@stylable/node`, that cause a regression in performance when we disabled the timed cache.

fix(node): add resolver cache to require hook

---

packages/experimental-loader/package.json
packages/experimental-loader/src/stylable-transform-loader.ts
yarn.lock

Use the new no source map runtime of css-loader@6.3.0

fix(experimental-loader): adopt css-loader API changes

---

packages/core/src/stylable-mixins.ts
packages/core/src/stylable-processor.ts
packages/core/src/stylable-value-parsers.ts
packages/core/test/diagnostics.spec.ts
packages/core/test/mixins/js-mixins.spec.ts
packages/core/test/stylable-value-parsers.spec.ts

Currently are parsing the arguments of a any mixin in the process step and we figure out the strategy via the import type
if it's `.css` we choose `named` strategy for the rest `args`.
This is wrong since JS mixins can be exported from a stylesheet and then we choose the wrong strategy for them (`named`).
This PR keeps the old parsing of options (hopefully for a shot term) but reparse the args right after we actually know what type of mixin it is.
This PR also fixes an issue that we did not resolve the mixin deeply to figure out the origin.

fix(core): js mixin re-export arguments parsing

---

packages/webpack-extensions/src/create-metadata-stylesheet.ts
packages/webpack-extensions/src/index.ts
packages/webpack-extensions/src/stylable-manifest-plugin.ts
packages/webpack-extensions/src/types.ts
packages/webpack-extensions/test/e2e/manifest.css-vars.spec.ts
packages/webpack-extensions/test/e2e/projects/manifest-plugin/Button.comp.st.css
packages/webpack-extensions/test/e2e/projects/manifest-plugin/webpack.css-vars.config.js

In order to allow import of named symbols inside variant files, generated by editing tools. This PR added the ability to generate the propper exports when generating index file in the manifest plugin.
We also provide a helper function `generateCssVarsNamedExports` to generate exports for all css vars of a stylesheet

feat(webpack-extensions): add ability to generate named exports in manifest index

---

packages/core/src/index.ts

They will still marked as deprecated but no logs will be fired on usage

refactor: remove deprecation logs from matchSelectorTarget and createSubsetAst

---

packages/core/src/index.ts
packages/core/src/module-resolver.ts
packages/core/src/stylable-resolver.ts
packages/rollup-plugin/test/projects/simple-stylable/index.st.css

Today we use the resolver cache and the value of its entities is very limited.
This PR extends the current cache entity value.
I found a minor issue in the rollup test that used `.js` when did not need.

refactor(core): extend resolver cache entity

---

packages/core/src/index.ts
packages/core/src/stylable-imports-tools.ts

So it turn out editing tools will need to parse stylable imports.

feat(core): export `parseStylableImport`

---

packages/core/src/helpers/deprecation.ts

Somehow in jest our module evaluated multiple times and tries to set the deprecation field twice and fail since it's not configurable. this PR changes the property to be configurable

fix(core): set the property of setFieldForDeprecation to be configurable

---

README.md
package.json
yarn.lock

We're currently only using `lerna` for its versioning capabilities. We can continue to do so using `npx` and not bring in a load of unneeded dependencies. Ideally, this would also be replaced by `pleb` at some point.

refactor: remove lerna dependency

---

packages/jest/src/index.ts
packages/jest/src/jest.ts
packages/jest/test/jest.spec.ts

While adding the configuration options in #2097, I made a mistake and created an incompatible API. This PR restores functionality to our Jest integration.
This also highlights the fact that we do not have real e2e tests for this integration.

fix(jest): correct export to match Jest API expectation

---

packages/core/src/native-reserved-lists.ts
packages/core/src/pseudo-states.ts
packages/core/src/stylable-processor.ts
packages/core/test/pseudo-states.spec.ts
packages/core/test/stylable-processor.spec.ts

We have a regression that can potentially pick up `custom pseudo states` with parameter which matches an `element` for a value with a first capital letter or a `class` for a value that starts with a dot (e.g. `:custom(Comp)` or `:custom(.part)`).
That might cause unintended symbol conflict that reports a `error/warning` diagnostics and even cause transpilation errors.
The fix:
- skip analyze of nested AST of unknown functional pseudo classes (that contain selectors)
- add the other native pseudo-classes to the restricted list - this is a breaking change that disallows states with the names:  `host`, `host-context`, `nth-child`, `nth-last-child`, `nth-of-type`, and `nth-last-of-type`. 
```css
:not(Comp.part) {}
:custom(Xxx.yyy) {}
```
In the example, `Comp` type and `part` class symbols …

fix(core): restrict functional nested selectors analyze

---

packages/e2e-test-kit/README.md

Came across a broken link when looking at e2e-test-kit package readme.

docs(e2e-test-kit): Fix broken link in readme

---

packages/core-test-kit/package.json
packages/core-test-kit/src/generate-test-util.ts
packages/core-test-kit/src/index.ts
packages/core/src/stylable.ts
packages/core/src/types.ts
packages/core/test/stylable.spec.ts

We want to have the option to filter out specific cache entries instead of invalidating all the cache at once.
I also added more cache tests that were missing.

feat(core): stylable resolver cache filter

---

packages/core/src/stylable-mixins.ts
packages/core/test/mixins/css-mixins.spec.ts

Version `4.9.0` introduced a regression with mixins that can cause stylable `meta` to become corrupted.
This PR resolves this regression.

fix(core): fix regression in inherited mixin flow

---

packages/webpack-plugin/src/plugin.ts
packages/webpack-plugin/src/types.ts
packages/webpack-plugin/test/e2e/browser-field.spec.ts
packages/webpack-plugin/test/e2e/projects/browser-field/node_modules/test-components/cjs/button.js
packages/webpack-plugin/test/e2e/projects/browser-field/node_modules/test-components/cjs/button.st.css
packages/webpack-plugin/test/e2e/projects/browser-field/node_modules/test-components/esm/button.js
packages/webpack-plugin/test/e2e/projects/browser-field/node_modules/test-components/esm/button.st.css
packages/webpack-plugin/test/e2e/projects/browser-field/src/app.st.css
packages/webpack-plugin/test/e2e/projects/browser-field/src/index.js

It turns out that the internal stylable resolver did not resolve stylable files **internal** requests according to the webpack target and the package.json browser field.
The test that checked this support was actually only tested the resolution of stylable requests from the JavaScript side. 
This PR fixes this issue but has one drawback:
JavaScript mixins and formatters are now also respect the browser field. This is not great because they run in node during the build but also not that bad because we can assume that no one is going to map them in the browser field.

fix(webpack-plugin): fix support of browser field

---

packages/core-test-kit/src/generate-test-util.ts
packages/core/src/stylable-transformer.ts
packages/core/test/stylable-transformer/post-process-and-hooks.spec.ts
packages/core/test/stylable-transformer/transformer.unit.spec.ts

After removing the timed cache. I forgot that the jest integration and some other flows are now not caching the stylable symbol resolution. This PR fixes it for all flows.

fix(core): enable resolver cache by default for the transform process

---

packages/webpack-plugin/src/plugin-utils.ts
packages/webpack-plugin/src/plugin.ts
packages/webpack-plugin/test/e2e/duplicate-namespace-warning.spec.ts
packages/webpack-plugin/test/e2e/projects/duplicate-namespace-warning/src/index.js
packages/webpack-plugin/test/e2e/projects/duplicate-namespace-warning/src/index.st.css
packages/webpack-plugin/test/e2e/projects/duplicate-namespace-warning/src/same-index.st.css
packages/webpack-plugin/test/e2e/projects/duplicate-namespace-warning/webpack.config.js

This PR add the ability to set DUPLICATE_MODULE_NAMESPACE to `warn` and not break the build
TODO:

feat(webpack-plugin): add ability to report DUPLICATE_MODULE_NAMESPACE as warning

---

packages/language-service/src/lib/service.ts
packages/language-service/test/lib/completions/completion.spec.ts
packages/language-service/test/test-kit/asserters.ts
packages/language-service/test/test-kit/stylable-in-memory-lsp.ts

fix(language-service): stylable completions should be sorted above css completions

---

packages/e2e-test-kit/src/cli-test-kit.ts

This PR adds 3rd `junction` option to symlinkSync in the CLI test kit in order to fix symlinks on windows without permissions

fix(e2e-test-kit): `junction` option for symlinks

---

package-lock.json
package.json
packages/webpack-plugin/src/plugin-utils.ts

while the interface of GeneratorContext clearly states that getData is optional, webpack's new version uses it as it was required. this is one of the downsides of them using ts-in-js with less strictness.
fix is to provide it with an actual map and extract the data uri from there when it's available. kept regex-matching fallback for older versions.

fix(webpack-plugin): crash with webpack@5.66.0

---

packages/core-test-kit/README.md
packages/core-test-kit/src/index.ts
packages/core-test-kit/src/inline-expectation.ts
packages/core-test-kit/src/test-stylable-core.ts
packages/core-test-kit/test/inline-expectations.spec.ts
packages/core-test-kit/test/test-stylable-core.spec.ts

This PR adds a single test util `testStylableCore` to the `@stylable/core-test-kit` which provides a single function to test all cases. solves: #1987 .
- add `@transform-remove` to test a node was removed in output
- throw when transformation expectations are performed on removed nodes
- fix parenthesis bug in `@rule` declaration expectation

Unify tool to test stylable core

---

packages/core/src/stylable-transformer.ts
packages/core/test/stylable-transformer/scoping.spec.ts

Calling `scopeSelectorAst` is mutative to the input AST. The new selector parser refactor introduced a flaw that we missed - the original input nodes are still mutated, but any addition AST is not inserted into the original input.
This has caused a regression that misses the space added before most pseudo-elements. for example:
`:is(Btn::label)` should be `:is(.btn .label)` and not `:is(.btn.label)`
This PR changes the behavior to be fully mutative, so that any inner changes or additions will now change the original input.
In addition this PR also removes an unwanted space before nested selector: 
`:is(::part)` is now transformed to `:is(.part)` instead of `:is( .part)`

fix(core): complex selectors inside nested pseudo-classes

---

packages/core/src/index.ts
packages/core/src/process-declaration-functions.ts
packages/core/src/stylable-transformer.ts
packages/runtime/src/index.ts
packages/runtime/src/types.ts

Exporting `StVar` type since it's a public API

fix: export `StVar` type

---

.github/workflows/tests.yml

installing 8.4.0 is broken on Windows, apparently. reported upstream

infra(ci): pin npm to 8.3.x

---

packages/cli/src/cli.ts
packages/cli/src/config/resolve-options.ts
packages/cli/src/types.ts

Our CLI clears the terminal in watch mode update a file update ([depending on the OS](https://nodejs.org/api/console.html#consoleclear)), one may want to keep the log for a variety of reasons.
This PR introduces a flag for the CLI to preserve the output.

feat(cli): preserve watch output

---

packages/cli/README.md
packages/cli/src/build-single-file.ts
packages/cli/src/config/resolve-options.ts
packages/cli/test/build.spec.ts
packages/cli/test/cli.spec.ts
packages/module-utils/src/generate-dts-sourcemaps.ts
packages/module-utils/test/sourcemap.spec.ts

- update docs
- - [x] CLI README file.
- - [x] CLI `help` output.

feat: set specific source file path in the `dts` source-maps

---

package-lock.json
package.json
packages/rollup-plugin/test/test-kit/rollup-runner.ts

Rollup introduced a [fix](https://github.com/rollup/rollup/releases/tag/v2.70.0) to an issue we had while trying to add a feature to the Stylable rollup plugin (#2342)

chore(deps): upgrade rollup to latest stable

---

packages/core/src/custom-values.ts
packages/core/src/features/css-class.ts
packages/core/src/features/css-custom-property.ts
packages/core/src/features/css-keyframes.ts
packages/core/src/features/css-type.ts
packages/core/src/features/feature.ts
packages/core/src/features/st-var.ts
packages/core/src/functions.ts
packages/core/src/index.ts
packages/core/src/stylable-mixins.ts
packages/core/src/stylable-resolver.ts
packages/core/src/stylable-transformer.ts
packages/core/test/diagnostics.spec.ts
packages/core/test/features/css-class.spec.ts
packages/core/test/features/st-var.spec.ts
packages/core/test/stylable-transformer/exports.spec.ts

This PR moves the resolvement of stylesheet symbols to be cached and resolved at a single place. In the future the cache can be moved out of transformation and invalidated on content / dependency change.
- use `getResolvedSymbols` with all symbols

refactor: resolve/cache all symbols together in transformation

---

packages/rollup-plugin/README.md
packages/rollup-plugin/src/index.ts

Apparently, rollup doesn't have `rootDir` like other bundlers (webpack, vite, etc...) and the context is referring to something else.
In this fix, we expose a way to set `projectRoot` and we default to `process.cwd()`
Relevant issues:
https://github.com/rollup/rollup/issues/4435

fix(rollup-plugin): use the correct base directory as `projectRoot`

---

README.md

Adding a banner to support our colleagues from Kyiv, Dnipro, and Lviv. Detox, RN Navigation, and other Wix's OSS projects have already done that.

Add StandWithUkraine banner

---

packages/core/src/features/st-symbol.ts
packages/core/src/helpers/rule.ts
packages/core/src/stylable-meta.ts
packages/core/src/stylable-mixins.ts
packages/core/src/stylable-transformer.ts
packages/core/test/helpers/rule.spec.ts
packages/core/test/mixins/css-mixins.spec.ts

This PR fixes 2 issues:
The issue happens when a mixed class is compounded with `.root:state` (root class with `custom-pseudo-class`). The issue is that there is a bug in the process of mixin that loses the actual root symbol when a stylesheet class other then root is mixed:
**mixin.st.css:**
```
.root {
-st-mixin: x;
}
.root:x.mix {
color: green;
}
```
**entry.st.css:**
```
@st-import [mix] from "./mixin.st.css";
/* @rule[1] .entry__c.mixin__root.mixin--x */
.c {
-st-mixin: mix;
}
```
valid selector: `.entry__c.mixin__root.mixin--x`
error selector: `.entry__c.mixin__root:x` // root symbol is "wrongly" replaced with mix class and `:x` custom-pseudo-state is unresolved
When compound selectors are connected after mixin class, they need to move to the beginning of the selector with the mixin …

fix: cases with mixin moved compound selector

---

packages/core-test-kit/src/test-stylable-core.ts
packages/core/src/custom-values.ts
packages/core/src/features/st-var.ts
packages/core/src/functions.ts
packages/core/src/index.ts
packages/core/src/stylable-resolver.ts
packages/core/src/stylable.ts
packages/core/test/features/st-var.spec.ts

New public API to get the computed Stylable vars for a given style sheet.
* Add the ability to require Stylable core package from the `core-test-kit`.
* Expose `flattenValue` from `CustomValueExtension` to indicate that the custom value can be flat.
* Move custom values resolution from each function evaluation to the resolver.

feat(core): get `st-vars` computed values

---

packages/create-stylable-app/src/create-project.ts
packages/create-stylable-app/template/ts-react-rollup/README.md
packages/create-stylable-app/template/ts-react-rollup/rollup.config.cjs
packages/create-stylable-app/template/ts-react-rollup/stylable.config.js
packages/create-stylable-app/template/ts-react-rollup/template.js
packages/create-stylable-app/template/ts-react-rollup/tsconfig.json
packages/create-stylable-app/template/ts-react-rollup/typings/globals.d.ts
packages/create-stylable-app/template/ts-react-webpack-lean/README.md
packages/create-stylable-app/template/ts-react-webpack-lean/stylable.config.js
packages/create-stylable-app/template/ts-react-webpack-lean/template.js
packages/create-stylable-app/template/ts-react-webpack-lean/tsconfig.json
packages/create-stylable-app/template/ts-react-webpack-lean/typings/globals.d.ts
packages/create-stylable-app/template/ts-react-webpack-lean/webpack.config.js
packages/create-stylable-app/template/ts-react-webpack/README.md
packages/create-stylable-app/template/ts-react-webpack/stylable.config.js
packages/create-stylable-app/template/ts-react-webpack/template.js
packages/create-stylable-app/template/ts-react-webpack/tsconfig.json
packages/create-stylable-app/template/ts-react-webpack/typings/globals.d.ts
packages/create-stylable-app/template/ts-react-webpack/webpack.config.js
packages/create-stylable-app/typings/template.d.ts

After we introduced the option you use `stc` in our integration https://github.com/wix/stylable/pull/2342, this PR adds this ability to our templates.
We can now generate Stylable stylesheets declaration files to give the users a strong typed experience when using Stylable and Typescript together seamlessly.
> This process requires the users to "run" their integration while developing.

feat(create-stylable-app): add `stcConfig` to the integrations templates

---

packages/cli/src/build-stylable.ts
packages/cli/src/config/resolve-options.ts
packages/cli/test/cli.spec.ts
packages/cli/test/config-options.spec.ts

feat(cli): remove default `cjs` format

---

packages/core/src/features/st-mixin.ts
packages/core/test/features/st-mixin.spec.ts

This PR fixes a regression that was introduced in the mixins analyze data. The `meta.mixins`, originally holds the list of all mixins in a stylesheet, was wrongfully pushed more definitions during the transform phase.
Notice that `meta.mixins` is deprecated and will be removed soon in `v5`

fix: collect `meta.mixins` only during analyze

---

packages/cli/README.md
packages/cli/src/base-generator.ts
packages/cli/src/build-single-file.ts
packages/cli/src/build.ts
packages/cli/src/config/resolve-options.ts
packages/cli/src/index.ts
packages/cli/src/types.ts
packages/cli/test/fixtures/named-exports-generator.ts
packages/cli/test/fixtures/test-generator.ts
packages/cli/test/generate-index.spec.ts

* It's possible to create an index file with additional output file formats.
* The index file will target the output st.css if it exists.
* `Base` symbol removed from the CLI index file.
* `IndexGenerator` API parameters changes.
closes #2470

feat(cli): generate index file with other outputs; `IndexGenerator` refactor

---

packages/core/src/features/css-type.ts
packages/core/test/features/css-class.spec.ts

This PR clarifies some intentions related to analyzing value interpolation into a custom pseudo class:
- **chore**: remove unrequired code that relates to an exception for unsupported functional type selector (e.g. `div()`) - The code is no longer required as nested selectors of custom pseudo-classes are not processed deeply (e.g. `:myState(value(myVar))`).
- **test**: add tests to indicate future intentions relating to mixins ability to template `st-var` definition & call.
for example:
```css
:vars {
myVar: b;
overrideVar: c;
}
.mix {
-st-states: x(enum(a, value(myVar)));
}
.mix:x(value(myVar)) {}
/* rule[1] .entry__into.entry---x-1-c*/
.into {
-st-mixin: mix(myVar (overrideVar))
}
```

chore(core): st-state with value interpolation intentions  

---

packages/core/src/features/css-class.ts
packages/core/src/features/css-custom-property.ts
packages/core/src/features/css-type.ts
packages/core/src/features/feature.ts
packages/core/src/features/index.ts
packages/core/src/features/st-import.ts
packages/core/src/features/st-scope.ts
packages/core/src/features/st-var.ts
packages/core/src/helpers/rule.ts
packages/core/src/stylable-meta.ts
packages/core/src/stylable-processor.ts
packages/core/test/features/css-custom-property.spec.ts
packages/core/test/features/st-custom-selector.spec.ts
packages/core/test/features/st-namespace.spec.ts
packages/core/test/scope-directive.spec.ts

This PR refactor the AST modifications that occur in the processor to prepare them to be moved to the transformer
- modifiers

refactor(core): prepare process AST mods for move to transform

---

packages/core/src/helpers/ast.ts
packages/core/src/index-internal.ts
packages/core/test/helpers/ast.spec.ts
packages/language-service/src/lib/css-service.ts
packages/language-service/src/lib/diagnosis.ts
packages/language-service/src/lib/utils/postcss-ast-utils.ts
packages/language-service/test/lib/diagnostics.spec.ts

fix(language-service): filter out false diagnostics for st-scope selectors with special characters

---

packages/core/src/helpers/namespace.ts
packages/core/src/index.ts
packages/core/src/resolve-namespace-factories.ts
packages/core/src/stylable-processor.ts
packages/core/test/helpers/namespace.spec.ts
packages/node/src/index.ts
packages/node/src/resolve-namespace.ts
packages/webpack-plugin/src/plugin.ts

Implement new universal namespace strategy
Features: 
* custom hash function
* custom hash length strategy
* custom/optional package info
* better hook interface for complex namespace generation
This strategy should support our existing node, no collision and default strategy  
Should close:
- https://github.com/wix/stylable/pull/2516
- #2286
Should handle:
- https://github.com/wix/stylable/pull/2313
TODO:
Notes:
This strategy should not treated as breaking change unless someone was depending on the current hash (murmur) output. 
We still need to check if we don't use `namespace\d+` regexp in out solutions like:
* packages\webpack-extensions\test\e2e\metadata-loader-case.spec.ts
* packages\webpack-plugin\test\e2e\dev-mode-warnings-project.spec.ts
* …

feat: implement new namespace strategy

---

packages/core/src/cached-process-file.ts
packages/core/src/create-stylable-processor.ts
packages/core/test/cached-process-file.spec.ts
packages/core/test/stylable-resolver.spec.ts

After noticing mtime based cache can lead to unexpected false negative.
This PR removes the mtime based caching in the cachedProcessFile

fix: cachedProcessFile should not based on mtime

---

packages/core/src/functions.ts
packages/core/test/features/st-mixin.spec.ts

This PR fixes the bug reported in #2553 - by un-escaping mixin arguments before applying them.

fix(core): unescape intended quotes in mix arg

---

packages/core/src/features/st-var.ts
packages/core/src/stylable-transformer.ts
packages/core/src/stylable.ts
packages/core/test/stylable.spec.ts

This PR adds the ability to pass override stylable vars through transformer options using a new `stVarOverride` arg. This is useful for the new top level APIs: `stylable.transform` and `stylable.transformDecl` that were missing the ability that existed previously when accessing the transformer directly.

feat(core): override st-vars with transformer options

---

packages/webpack-plugin/src/plugin-utils.ts
packages/webpack-plugin/test/e2e/duplicate-namespace-perserve-modules.spec.ts
packages/webpack-plugin/test/e2e/projects/duplicate-namespace-perserve-modules/src/index.js
packages/webpack-plugin/test/e2e/projects/duplicate-namespace-perserve-modules/src/unused.st.css
packages/webpack-plugin/test/e2e/projects/duplicate-namespace-perserve-modules/src/used.st.css
packages/webpack-plugin/test/e2e/projects/duplicate-namespace-perserve-modules/webpack.config.js

In a complex project using complex namespacing strategies - we have encountered a situation where there is a duplicate module that in one case appears to be used, and in the other, appears to be unused - this caused our optimizer to drop the used module. 
This fix should preserve any conflicting module that is `used` so that it is included in the final output.

fix(webpack-plugin): preserve duplicate used/unused conflict

---

packages/create-stylable-app/template/ts-react-rollup/.eslintrc
packages/create-stylable-app/template/ts-react-webpack-lean/.eslintrc
packages/create-stylable-app/template/ts-react-webpack/.eslintrc

instead of explicitly turning off "react/react-in-jsx-scope".
see:
https://github.com/jsx-eslint/eslint-plugin-react#configuration
https://github.com/jsx-eslint/eslint-plugin-react/blob/b9aa04b10d9bb0b7274ad314ca125ddefd9fbdb3/index.js#L171

refactor(templates): enable react/jsx-runtime

---

packages/build-tools/src/load-stylable-config.ts
packages/cli/test/config-options.spec.ts

to better support projects that move to "type": "module" (in package.json), allow stylable configuration file to be named stylable.config.cjs (exporting a commonjs module).
unfortunatly, stylable cannot currently support mjs config. the config loading function is sync, and we would need to import() that file if we want to support mjs.

feat: load stylable.config.cjs as well

---

packages/core/src/features/st-mixin.ts
packages/core/test/features/st-mixin.spec.ts

This PR exposes the API to combine 2 selectors according to how stylable mixins selectors are combined (different then [CSS nesting](https://www.w3.org/TR/css-nesting-1/)). 
The API is available on stylable:
```js
stylable.stMixin.scopeNestedSelector(scopeSelector: string, nestSelector: string): string;
```

feat(core): st-mixin scope nested rule public API

---

packages/core/src/features/st-scope.ts
packages/core/src/index.ts
packages/core/src/stylable.ts
packages/core/test/features/st-scope.spec.ts

This PR adds an API to find the `@st-scope` atrule of a nested rule from source AST. The API is available on stylable instance:
```js
const stScope = stylable.stScope.getStScope(rule);
```

feat(core): public API to get st-scope atrule

---

packages/create-stylable-app/template/ts-react-rollup/.eslintrc
packages/create-stylable-app/template/ts-react-rollup/template.js
packages/create-stylable-app/template/ts-react-webpack-lean/.eslintrc
packages/create-stylable-app/template/ts-react-webpack-lean/template.js
packages/create-stylable-app/template/ts-react-webpack/.eslintrc
packages/create-stylable-app/template/ts-react-webpack/template.js

Our introduction of `.d.ts` file generation in our `create-stylable-app` templates have made the use of our `eslint-stylable-plugin` redundant. TypeScript provides a better experience out of the box.

fix(create-stylable-app): remove stylable eslint plugin

---

packages/cli/src/build-single-file.ts
packages/core/src/stylable.ts
packages/core/test/stylable.spec.ts
packages/experimental-loader/src/stylable-transform-loader.ts
packages/module-utils/src/module-factory.ts
packages/rollup-plugin/src/index.ts
packages/webpack-plugin/src/loader.ts

This PR simplify the `stylable.transform`:
Change signature from accepting either `meta or source+path` to accepting `meta or path`. The new signature is inline with other top level transform functions like `transformSelector` or `transformDecl`. 
To transform custom source on specific context path now you first need to create a `meta` and pass it to the transform method: `stylable.transform(stylable.analyze(path, source), {/*optional transform options*/})`
This also fix a Typescript issue that the old signature could theoretically accept transform options, but couldn't in reality since they weren't in the typescript signature.
Calling transform used to replace the file processor cache with whatever was passed in. That means that potential override content that was not synced with …

refactor!: simplify `stylable.transform` API (v5)

---

packages/core/src/features/css-class.ts
packages/core/src/stylable.ts
packages/core/test/features/css-class.spec.ts

This PR exposes public API to transform a stylesheet class into its final selector.
- support both local & imported classes
- support global via `-st-global` declaration
- return `undefined` for unknown or non class symbols
> NOTE: passing class name that is declared within global (`:global(.class)`) returns undefined as `:global` selector doesn't register symbols atm.

feat(core): public transform class API

---

packages/core/src/deprecated/deprecated-selector-utils.ts
packages/core/src/helpers/selector.ts
packages/core/src/index-deprecated.ts
packages/core/src/stylable-processor.ts
packages/core/test/diagnostics.spec.ts
packages/language-service/test/lib/diagnostics.spec.ts

Since we really don't know how the stylesheet would be used, we might not want to make assumptions on where the `root` class is location in a selector.
for example portals, where I place the `root` class on known local class like `popover-content`

fix: remove root validation

---

packages/create-stylable-app/template/ts-react-rollup/template.js
packages/create-stylable-app/template/ts-react-webpack-lean/template.js
packages/create-stylable-app/template/ts-react-webpack/template.js
packages/rollup-plugin/package.json
packages/webpack-plugin/package.json

All packages that used @stylable/core as peer dependency also depends on packages that depend on @stylable/core directly

chore: move core to dependencies

---

packages/runtime/src/inject-styles.ts

fix an edge case were injecting a stylesheet duplicate of an already injected stylesheet **with lower depth** causes an unexpected error to be thrown.
This is no easily reproducible since it requires multiple builds of the same project with multiple versions to be loaded together (not an ideal production strategy, but we found a project that encounter it). 
simple case fail:
inject('ns', 1)
inject('ns', 0) <-- error
> Note: this is a fix for v5, a similar fix for v4 also exist here #2620

fix: js runtime explode in edge case with involving multiple builds

---

packages/cli/README.md
packages/cli/src/code-mods/load-codemods.ts
packages/cli/src/code-mods/namespace-to-st-namespace.ts
packages/cli/test/codemods/namespace-to-st-namespace.spec.ts
packages/cli/test/fixtures/named-exports-generator.ts
packages/cli/test/generate-index.spec.ts
packages/core/src/features/feature.ts
packages/core/src/features/index.ts
packages/core/src/features/st-namespace.ts
packages/core/src/stylable-meta.ts
packages/core/src/stylable-processor.ts
packages/core/test/features/st-namespace.spec.ts
packages/core/test/stylable-processor.spec.ts
packages/core/test/stylable-resolver.spec.ts
packages/language-service/src/lib/completion-providers.ts
packages/language-service/src/lib/completion-types.ts
packages/language-service/src/lib/css-service.ts
packages/language-service/test/fixtures/server-cases/imports/top-level-import-exists.st.css
packages/language-service/test/lib/completions/namespace-directive.spec.ts
packages/language-service/test/test-kit/completions-asserters.ts
packages/webpack-plugin/test/e2e/projects/3rd-party-standalone/src/index.st.css
packages/webpack-plugin/test/e2e/projects/4th-party-project/src/index.st.css
packages/webpack-plugin/test/e2e/projects/duplicate-namespace-warning/src/index.st.css
packages/webpack-plugin/test/e2e/projects/duplicate-namespace-warning/src/same-index.st.css
packages/webpack-plugin/test/e2e/projects/duplicate-namespace/src/index.st.css
packages/webpack-plugin/test/e2e/projects/duplicate-namespace/src/same-index.st.css

This PR adds support for `@st-namespace` that was added in v5 to v4
- added to v5 in #2624

feat(core) transition from native `@namespace` - v4

---

.github/workflows/tests.yml

Limit CI test job timeout to a reasonable value. the [default is 360](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idtimeout-minutes) while our test take ~4-7 minutes.
Limiting it to 15 minutes to prevent any buggy/flaky unexpected issues from running too long or even until memory overflows.

infra: lower CI test job timeout

---

packages/e2e-test-kit/src/project-runner.ts
packages/webpack-plugin/test/e2e/deep-js.spec.ts
packages/webpack-plugin/test/e2e/stc-watched-project.spec.ts

This PR fixes a flakiness with tests that use the `projectRunner` inner async step `actAndWaitForRecompile` with low default timeout in their validate state (or no timeout handling).
**Changes**
**Could improve in the future**
The solution is not ideal, it would be better to start with a minimal total time and increase the timeout for each async step. But (1) Mocha timeout API doesn't allow changing the timeout during test, and (2) wrapping mocha test with a custom timeout is not simple without wrapping the `it` functions themselves, or adding test lifecycle to the `projectRunner`.

infra(e2e-test-kit): default project runner inner step timeout flakiness

---

packages/language-service/src/lib/css-service.ts
packages/language-service/test/lib/completions/custom-property.spec.ts

This PR adds the `@property` at-rule to the ignore list of `unknown at-rules` coming from the `vscode-css-languageservice`

fix(lsp): `@property` unknown at-rule diagnostic

---

packages/core/src/stylable-resolver.ts
packages/core/test/stylable-resolver.spec.ts

Fix regression that caused Stylable to hit the underlying resolver more then once.

fix(core): fix resolver performance regression (v4)

---

packages/core/src/custom-values.ts
packages/core/test/features/st-var.spec.ts

This PR fixes a bug that prevented nesting referenced `value()` within a `st-map` var type:
```css
:vars {
list: st-array(red, green);
map: st-map(key value(list))
}
.a {
prop: value(map, key, 1) /* should return "green" */
/* before fix it evaluated to */
prop: st-array(red, green);
}
``` 
-----
In addition this also fixes the output from `stylable.stVar.getComputed` to return the unboxed value on the input field instead of the runtime value:
```css
:vars {
green: green;
inline: st-map(a red);
reference: st-map(a value(red));
}
```
So that `stylable.stVar.getComputed(meta)` returns `inline` and `reference` with the same value:
```js
// correct result after fix:
{
value: { a: 'green' },
input: {
type: 'st-map',
value: {
a: {
flatValue: 'green',
type: 'st-string',
value: 'green',
},
},
} …
```

fix(core): allow value reference in st-map

---

packages/webpack-plugin/src/index.ts
packages/webpack-plugin/src/webpack-config-stylable-excludes.ts

This is to make [using NextJS with Stylable](https://stylable.io/docs/getting-started/nextjs-integration/) easier, and to avoid users having to inline the function in their configuration.

feat(webpack-plugin): expose function to bundle libs according to config

---

packages/jest/src/jest.ts
packages/jest/test/jest.spec.ts

Jest have changed their [transformer API](https://jestjs.io/docs/code-transformation#writing-custom-transformers) in v28, so that it now expects an object to be returned (instead of a string), with the `code` field holding the transformed source.
This approach has been long supported on Jest, but not required, and so we're now moving to the new response structure.
This PR has been tested to work with versions as old as jest v22, and requires no change from our users.
Fixes: #2707

fix(jest): process output matches new api

---

packages/core/src/features/css-class.ts
packages/core/src/helpers/rule.ts
packages/core/src/stylable-transformer.ts
packages/core/test/features/css-class.spec.ts
packages/core/test/stylable-transformer/scoping.spec.ts
packages/webpack-plugin/test/e2e/dev-mode-warnings-project.spec.ts

This PR fix dev inherit rule for parts with `-st-global`. Before this change, the check selector would ignore the global selector and would always fail the check.
In addition this PR refactor the code to make it simpler and move it into the CSS class feature.

fix: dev inherit check with global selector

---

packages/core/src/features/css-class.ts
packages/core/test/features/css-class.spec.ts
packages/optimizer/src/stylable-optimizer.ts
packages/optimizer/test/ast-optimizations.spec.ts
packages/webpack-plugin/test/e2e/globals.ts
packages/webpack-plugin/test/e2e/projects/globals/src/index.js
packages/webpack-plugin/test/e2e/projects/globals/src/index.st.css
packages/webpack-plugin/test/e2e/projects/globals/src/node_modules/test-components/lib.st.css
packages/webpack-plugin/test/e2e/projects/globals/src/node_modules/test-components/package.json
packages/webpack-plugin/test/e2e/projects/globals/webpack.config.js

This PR fix issues relating to global classes getting lost in production mode.
- keep track of `meta.globals` from an extended class with `-st-global` value
- reserve global mapping for exports while optimizing class names

fix: production mode globals

---

packages/core-test-kit/src/inline-expectation.ts
packages/core-test-kit/test/inline-expectations.spec.ts

This PR adds the ability to test for empty declaration value within an inline expectation.
A "Malformed declaration expectation" error is still thrown for:
- just a prop: `color`
- missing prop: `: red`

test: allow to inline test for empty decl value

---

package-lock.json
package.json
packages/rollup-plugin/package.json
pleb.config.mjs

This PR upgrades Rollup to version 3. The `@stylable/rollup-plugin` package is now tested with the new version, but the peer dependency is set to both `^2.70.0` or `^3.0.0` because I can't see any breaking change that might fail the plugin (and all tests are passing 😏).
@barak007 can you take a look at the [release notes](https://github.com/rollup/rollup/releases/tag/v3.0.0) and see if you can think of any issues that might we need to take under consideration? what about this one: `Rollup will no longer fix assets added directly to the bundle by adding the type: "asset" field`?

Support Rollup version 3

---

packages/rollup-plugin/README.md
packages/rollup-plugin/src/index.ts
packages/rollup-plugin/test/rollup-js-exports.spec.ts
packages/rollup-plugin/test/rollup-plugin-stylable.spec.ts

This PR adds the option to override the default Stylable configuration from the Rollup plugin.

feat(rollup): provide stylable config override

---

packages/language-service/src/lib/css-service.ts
packages/language-service/test/lib/completions/custom-property.spec.ts
packages/language-service/test/lib/completions/keyframes.spec.ts
packages/language-service/test/lib/completions/layer.spec.ts

This PR "hides" the `st-global()` in `@keyframes/@layer/@property` from the native CSS LSP that doesn't expect it to be there and fails on "identifier expected".
fixes: #2785

fix(language-service): st-global in at-rules definition

---

packages/webpack-plugin/src/loader.ts
packages/webpack-plugin/src/plugin.ts
packages/webpack-plugin/src/types.ts
packages/webpack-plugin/test/e2e/native-css.spec.ts
packages/webpack-plugin/test/e2e/projects/native-css/src/index.js
packages/webpack-plugin/test/e2e/projects/native-css/src/local.css

Since native CSS doesn't go through the transform flow, then global class names are not collected to be ignored when running stylable optimization. That caused native CSS class names to be lost in production transformation.
To fix that, this PR exclude native CSS stylesheets from any stylable optimization.

fix(webpack): preserve native CSS class names in production

---

packages/cli/src/build-single-file.ts
packages/core/src/stylable-transformer.ts
packages/core/src/types.ts
packages/core/test/features/css-class.spec.ts
packages/core/test/features/css-pseudo-class.spec.ts
packages/core/test/features/st-mixin.spec.ts
packages/experimental-loader/package.json
packages/experimental-loader/src/stylable-transform-loader.ts
packages/optimizer/src/stylable-optimizer.ts
packages/optimizer/test/stylable-optimizer.spec.ts
packages/webpack-plugin/README.md
packages/webpack-plugin/src/plugin.ts
packages/webpack-plugin/test/e2e/optimizations.spec.ts
packages/webpack-plugin/test/e2e/projects/optimizations/webpack.config.js

This PR moves the removal of `-st-*` declarations to be part of the transformation when used with `mode: production`. 
In addition the `removeStylableDirectives` configuration is removed and a `console.warn` with an appropriate deprecation/unrequired message is logged.

feat: remove stylable directives at transform

---

package-lock.json
package.json
packages/code-formatter/test/formatter.spec.ts
packages/code-formatter/test/tsconfig.json
packages/core-test-kit/src/deindent.ts
packages/core-test-kit/src/diagnostics.ts
packages/core-test-kit/src/index.ts
packages/core-test-kit/test/deindent.spec.ts
packages/core/package.json
packages/core/test/features/css-contains.spec.ts
packages/core/test/features/css-custom-property.spec.ts
packages/core/test/features/css-keyframes.spec.ts
packages/core/test/features/css-layer.spec.ts
packages/core/test/helpers/ast.spec.ts
packages/core/test/stylable.spec.ts
packages/language-service/test/lib/completions/contains.spec.ts
packages/language-service/test/lib/completions/custom-property.spec.ts
packages/language-service/test/lib/completions/keyframes.spec.ts
packages/language-service/test/lib/completions/layer.spec.ts
packages/language-service/test/lib/completions/namespace-directive.spec.ts
packages/language-service/test/lib/diagnostics.spec.ts
packages/language-service/test/tsconfig.json
packages/module-utils/test/sourcemap.spec.ts
packages/rollup-plugin/test/rollup-side-effects.spec.ts
packages/rollup-plugin/test/tsconfig.json

This PR removed the dependency on `deindent` package. It has several issues, like losing newlines and in some cases spaces, and in addition doesn't trim the first/last empty lines, making it harder to use.
- remove deindent as `@stylable/core` dependency - not sure why it wasn't a dev-dependency as it's only used in tests
- write alternative into `@stylable/core-test-kit`
- trim empty first/last lines
- remove indentation based on the minimal length of indentation before content
- preserve newlines and spaces
- replace all usages - had to add `core-test-kit` as a dependency to several test folders

chore: replace deindent dependency

---

.eslintrc
packages/build-tools/src/process-url-dependencies.ts
packages/cli/src/base-generator.ts
packages/cli/src/code-mods/namespace-to-st-namespace.ts
packages/cli/src/code-mods/st-global-custom-property-to-at-property.ts
packages/cli/src/code-mods/st-import-to-at-import.ts
packages/core/src/index-internal.ts
packages/module-utils/src/generate-dts-sourcemaps.ts
packages/runtime/src/index-internal.ts
packages/schema-extract/src/cssdocs.ts
packages/webpack-extensions/src/stylable-manifest-plugin.ts
packages/webpack-plugin/src/webpack-entities.ts

This PR adds a [lint rule](https://eslint.org/docs/latest/rules/no-restricted-imports) to make sure that imports from stylable packages are only requested from the main index or the intended internal-index between packages and not directly into `src/dist` paths.
- allow import from `@stylable/*`
- allow import from `@stylable/*/dist/index-internal` (dist should be removed once we move to package exports)
- allow internal path imports from test files

infra: enforce allowed import paths between packages

---

.vscode/launch.json
scripts/test-runner.js

- simplified launch.json: remove useless "Launch Program" and use "type": "node" (as recommended by vscode these days).
- fixed a type error about a variable used before assignment in test runner.

refactor: simpler mocha entrypoint resolution

---

packages/e2e-test-kit/src/cli-test-kit.ts

This PR clears the timeout that holds the process open when running the CLI using the CLI test-kit. Until now the timeout would hold the process open for ~10s even when the test succeeded. In vscode on OSX this kept the debug open indefinitely.

infra(cli): clear cli test timeout that hold process

---

packages/webpack-plugin/src/plugin.ts

This PR adds an experimental flag `experimentalAttachCssToContainingChunks` that changes the way the CSS asset is attached to webpack chunks - in the default (off mode), the result generated CSS asset is attached to entrypoint chunks, and when the flag is enabled, it attaches the CSS to every chunk that contains stylable stylesheet.  
This is primarily added to test a fix for Next 13 new experimental [app directory feature](https://beta.nextjs.org/docs/routing/fundamentals#the-app-directory) (raised in #2773). In the default mode Next resolve the attached generated CSS module mistakenly as a JavaScript file and attach it in the HTML as a script tag. 
**Notice 1:** I'm adding this experimental flag that seems to resolve the issue, although unfortunately nor NextJS or Webpack document how …

feat(webpack): experimental flag for next 13 app directory

---

packages/core/src/helpers/import.ts

Improve `tryCollectImportsDeep` by filtering only stylable stylesheets imports, preventing unnecessary (handled) throws over JS and other files.

fix(core): run collect imports deep only on stylable files

---

packages/core/src/features/css-media.ts
packages/core/src/features/feature.ts
packages/core/src/features/index.ts
packages/core/src/features/st-var.ts
packages/core/src/functions.ts
packages/core/src/stylable-transformer.ts

refactor: use only one walk in transform
refactor: move valueHook to evaluator

feat: css-media

---

packages/language-service/src/lib-new/features/ls-st-import.ts
packages/language-service/src/lib-new/lang-service-context.ts
packages/language-service/src/lib/completion-providers.ts
packages/language-service/src/lib/provider.ts
packages/language-service/src/lib/service.ts
packages/language-service/test/lib-new/features/ls-css-pseudo-class.spec.ts
packages/language-service/test/lib-new/features/ls-st-import.spec.ts
packages/language-service/test/test-kit/completions-asserters.ts
packages/language-service/test/test-kit/test-lang-service.ts

This PR adds path completions to the `@st-import` specifier.
- complete wild card with no filtering after
- default hard coded accepted conditional fields with simple dfs rule finding ("import", "require", "node", "browser", "default") 
- no `null` value filtering from result suggestions

feat(lsp): st-import specifier completions

---

packages/core/src/features/css-class.ts
packages/core/src/features/css-pseudo-class.ts
packages/core/src/features/css-type.ts
packages/core/src/features/st-global.ts
packages/core/src/helpers/selector.ts
packages/core/src/stylable-transformer.ts

Small change to allow running `scopeSelectorAst` without modifying the meta. This changes the transformation of classes with `-st-global` definition to transform into `:global(selector)` and to be collected like other global selectors at the end of the transformation process instead of registering the global classes within the process in a special way.
This is required in order to run selector transformation/inference without mutating the context meta.

refactor: move all global classes unwrap/collect to the end of transformation

---

packages/core/src/features/css-class.ts
packages/core/src/features/css-pseudo-class.ts
packages/core/src/features/css-type.ts
packages/core/src/features/feature.ts
packages/core/src/features/st-custom-selector.ts
packages/core/src/features/st-mixin.ts
packages/core/src/features/st-scope.ts
packages/core/src/helpers/custom-state.ts
packages/core/src/helpers/eql.ts
packages/core/src/helpers/selector.ts
packages/core/src/index-internal.ts
packages/core/src/stylable-transformer.ts
packages/core/src/stylable.ts
packages/core/test/features/css-pseudo-class.spec.ts
packages/core/test/features/css-pseudo-element.spec.ts
packages/core/test/features/css-type.spec.ts
packages/core/test/features/st-custom-selector.spec.ts
packages/core/test/features/st-global.spec.ts
packages/core/test/features/st-scope.spec.ts
packages/core/test/stylable-transformer/general.spec.ts
packages/language-service/src/lib-new/features/ls-css-pseudo-class.ts
packages/language-service/src/lib-new/lang-service-context.ts
packages/language-service/test/lib-new/features/ls-css-pseudo-class.spec.ts

This PR adds the inference for multiple selector types behinds a new experimental flag that enables support for transformation, validation and completion of cases that combine multiple selectors like: `@st-scope`, `@custom-selector`, `:is()`, `:where()`, `:nth-x(, )`, and future support of nested CSS and multiple extends. 
In addition the new flag is changing the behavior of combinators and other selector nodes so that they will reset the selector inferred type back to the inferred context. 
The flag is meant for testing in v5 and is intended to be the default behavior in the upcoming v6
- pseudo-class/element transformation
- class/element transformation
- mixin context
- language service completions
- remove old tracking code
- add `nth-child/nth-last-child` to list of pseudo-classes …

feat: support selector intersection

---

packages/create-stylable-app/template/ts-react-rollup/tsconfig.json
packages/create-stylable-app/template/ts-react-webpack-lean/tsconfig.json
packages/create-stylable-app/template/ts-react-webpack/tsconfig.json

regenerated tsconfig.json using ts@5. adjusted values a bit:
- target is es2020 (instead of es2019)
- lib now also includes dom.iterable, and matches target with es2020
- eol defaults to lf
- importsNotUsedAsValues got replaced with verbatimModuleSyntax
- noImplicitOverride is also set

fix(create-stylable-app): compat with ts@5.0+

---

packages/core/src/features/st-mixin.ts
packages/core/src/module-resolver.ts
typings/externals/index.d.ts

this ensures core can be bundled using esbuild to cjs/esm

refactor: make core compatible with esm bundling

---

packages/build-tools/src/index.ts
packages/build-tools/src/load-stylable-config.ts
packages/core-test-kit/src/index.ts
packages/core-test-kit/src/native-temp-dir.ts
packages/language-service/test/lib-new/features/ls-st-import.spec.ts
packages/language-service/test/test-kit/test-lang-service.ts
packages/node/loader.mjs
packages/node/package.json
packages/node/src/common.ts
packages/node/src/loader.ts
packages/node/src/require-hook.ts
packages/node/src/tsconfig.json
packages/node/test/loader.spec.ts
packages/node/test/tsconfig.json

This PR adds a NodeJS loader to be used with [--experimental-loader](https://nodejs.org/api/esm.html#loaders).
The new loader doesn't support node 14 since the loader API changed (tests are skipped for v14).
- How do we differ between dev/production mode (2 loaders?, env flag?)
- How do we provide optimized namespaces mappings from a seperate process like webpack? (same issue with `attachHook`, but a bit more difficult since loaders don't get args ) 
- Currently the loader generates an esm module, but imports the cjs runtime (`@stylable/runtime/dist/pure.js`). This is done because our esm runtime is built into `.js` and the runtime package.json is not `type:module`, which means that the esm version cannot be imported by node and is currencly only used by bundlers that are more lenient.

feat(node): experimental loader

---

packages/cli/test/watch-multiple-projects.spec.ts
packages/core/src/features/st-scope.ts
packages/core/src/index-internal.ts
packages/core/src/stylable-processor.ts
packages/core/src/stylable-transformer.ts
packages/core/test/diagnostic-codes.spec.ts
packages/core/test/stylable-processor.spec.ts
packages/core/test/stylable-transformer/nesting.spec.ts
packages/language-service/test/lib-new/features/ls-css-pseudo-class.spec.ts

This PR adds support for [native CSS nesting](https://drafts.csswg.org/css-nesting/).
Most of the work to support nesting was already done in the refactor to support [selector intersection](#2827 ).

feat: css nesting

---

packages/core/src/stylable-transformer.ts
packages/core/test/features/st-global.spec.ts
packages/core/test/features/st-scope.spec.ts
packages/core/test/stylable-transformer/general.spec.ts

This PR changes the inferred selector context under the new `experimentalSelectorInference` flag.
The default inferred selector context is used in 2 cases
- the starting point for any selector 
- reset after a combinator (with `experimentalSelectorInference`)
Before this change the inferred selector used was the stylesheet root, and this PR changes it to be a universal selector (behind the flag), which means that custom-pseudo-element/class cannot be floating:
```css
.root {
-st-states: state;
}
.part {}
/* all of these cases will now report unknown pseudo diagnostics and will not transform */
:state {}
::part {}
.x :state {}
.x ::part {}
```

feat: default to universal inferred context selector

---

packages/language-service/src/lib/completion-providers.ts
packages/language-service/test/lib-new/features/ls-st-import.spec.ts

This PR changes the completion provider to handle native css named import completions.

fix(lsp): named import completions from native css

---

packages/language-service/src/lib-new/edit-time-parser.ts

`EditTimeParser` extends `Parser`, which is defined in `typings/externals/index.d.ts` instead, use the exact types and ensure return type matches.
also exported `AnyNode`, as it's used in the return type.

fix(lang-service): ensure .d.ts contains no internals

---

packages/core/src/helpers/rule.ts
packages/core/test/features/st-mixin.spec.ts

This PR fix a regression bug (worked in v4) that causes `mixin` that is defined as part of `@st-scope` params to be mixed incorrectly.
The issue causes the original mixin class to be added as part of the selector instead of being replaced by the context selector.
For example:
```css
@st-scope .mix {
.x {}
}
.into {
-st-mixin: mix;
}
/* should transforms into */
.into .x {}
/* but is incorrectly transformed into */
.into .mix .x {}
```

fix: mixin of class from st-scope params

---

packages/core-test-kit/src/index.ts
packages/core-test-kit/src/postcss-node-asserts.ts
packages/core/src/features/st-mixin.ts
packages/core/src/helpers/rule.ts
packages/core/src/helpers/selector.ts
packages/core/src/stylable-transformer.ts
packages/core/src/stylable-utils.ts
packages/core/src/stylable.ts
packages/core/test/features/st-mixin.spec.ts
packages/core/test/helpers/rule.spec.ts
packages/core/test/helpers/selector.spec.ts
packages/language-service/test/test-kit/postcss-node-asserts.ts

Up until now, when a mixin fragment was created, Stylable used a nesting selector (`&`) internally to mark the mixin anchor that would be fused in transformation to the mixin target. This is conflicting with native CSS nesting in case the mixin has a nesting selector in it's source.
This PR refactors the internal selector that is used to mark the mixin anchor from `&` to `[st-mixin-marker]`, solving an issue with mixins that contain CSS nesting.
- Merges the transformed mixin fragment for nested rules
- fix: merge nested at-rules instead of flattening deep declarations
JS mixin uses `&` to reference the mix target anchor, which is a public API that cannot change. To support nesting in JS mixin, Stylable would have to offer a new mixin API that would provide some other way of referencing …

feat: support CSS nesting in CSS mixin

---

packages/language-service/test/lib-new/features/ls-css-pseudo-class.spec.ts
packages/language-service/test/lib-new/features/ls-st-import.spec.ts
packages/language-service/test/test-kit/test-lang-service.ts

This PR adds an additional way to create a completion expectation through a build function that provides that carets and edit-text expectation helpers

infra: lang service test kit completion function expectation

---

packages/language-service/src/lib-new/ast-from-position.ts
packages/language-service/src/lib-new/edit-time-parser.ts
packages/language-service/test/lib-new/ast-from-position.spec.ts
packages/language-service/test/lib-new/edit-time-parser.spec.ts

This PR fixes an internal bug with the `ast-from-position` for a case of unclosed at-rule at eof. Before this fix postcss would simply allow the unclosed at-rule without setting the `source.end` of the root node which caused the `ast-from-position` to ignore the unclosed at-rule.
This PR fixes:
- close all unclosed nodes at the end of safe parsing
- check for unclosed at-rule in `ast-from-position` 
- set minimum of one after the at-rule name as the params start value for the case where the space after the name is not entered yet: `@name|`

fix: edit parser unclosed at-rule bug

---

packages/language-service/src/lib-new/ast-from-position.ts
packages/language-service/test/lib-new/ast-from-position.spec.ts

This PR fix a couple of errors in `ast-from-position` that is used to identified source context for the language-service:
- fix: `@name |params` should resolve `where` to `atRuleParams` and not `atRuleBody`
- fix: resolve at-rule params the entire prelude including `afterName`, `params`, `between` (params and `;` or `{`), and potential space for last unclosed at-rule
- fix: resolve declaration value from including anything from colon, actual value, and potential space for last unclosed declaration
- chore : improve `deindent` config in test-kit

fix(lsp): ast-from-position fixes

---

packages/esbuild/src/build-cache.ts
packages/esbuild/src/debug.ts
packages/esbuild/src/stylable-esbuild-plugin.ts
packages/node/src/find-package-json.ts
packages/node/src/index.ts
packages/node/src/resolve-namespace.ts

Since esbuild has no cache we need to manually implement it for the plugin.
This PR implement cache (naively check any deep dependency) for the transformation of stylable files.
more to caching should be done to other hooks.

fix(esbuild): cache layer for the transform process

---

packages/language-service/src/lib-new/features/ls-st-import.ts
packages/language-service/src/lib-new/lang-service-context.ts
packages/language-service/src/lib/completion-providers.ts
packages/language-service/src/lib/provider.ts
packages/language-service/src/lib/service.ts
packages/language-service/test/lib-new/features/ls-st-import.spec.ts

This PR adds a way to allow stylable lsp plugins to check context before completion in order to take ownership of context and filter out other providers.
Currently implemented to filter out native-css service and selector completions from `@st-import` at-rule 
In addition a small refactor to change "provide" that would only be for completion into "lsp plugin" to group general lsp api around a feature/concept

feat(lsp): filter completions by context

---

packages/core/src/helpers/rule.ts
packages/core/test/features/css-class.spec.ts
packages/core/test/features/css-keyframes.spec.ts

This PR fix an unintended restriction on deep nested scope check within `@st-scope`. The intended use of `@st-scope` is to mark anything within it as scoped, including rules nested in media queries.

fix: `@st-scope` deep scoping

---

packages/esbuild/package.json
packages/rollup-plugin/src/index.ts

change esbuild peer dependency to `>=0.17.18` to allow any future version above `@stylable/esbuild` original check against version.
Since esbuild itself is in version 0 and breaking changes are allowed in minor, then it's fine have no upper limit.
When esbuild@1 is out we can release a version with an upper limit.
Try clearing the cache for relative `package.json`  to file on rebuild.
This is a trade off between speed and the need to re-execute the flow when packages are added/removed.
There are other integrations that don't clear this cache and we might want to think of a unified behavior
- maybe expose the cache control out of each integration and allow to fine tune the experience
- collect the possible resolved paths, listen for changes, and automatically fine-tune the invalidation

fix: peer dep + cache clear

---

packages/core/src/features/st-scope.ts
packages/core/test/features/st-scope.spec.ts
packages/core/test/scope-directive.spec.ts

This PR relaxes the restrictions on the usage of `@st-scope`, allowing it to be used solely for opting out of global side-effect restrictions. This means that there is no longer a need to prepend a scoping selector to any nested selectors.
The @st-scope directive offers two capabilities:
- It allows for opting out of `unscoped` selector diagnostics, which is useful for defining a theme or resetting with global side-effects.
- It reduces the repetition of selectors.
With native CSS nesting support, the second capability becomes redundant.
To address the opt-out feature more clearly, we can consider the following approaches:
1. Use eslint type instructions, such as `@st-ignore "unscoped"`.
2. Explicitly state the semantics of the stylesheet using statements like `@st-global, @st-theme, or …

feat: st-scope with no scoping selector

---

packages/core/src/features/st-mixin.ts
packages/core/test/features/st-mixin.spec.ts

This PR fixes a missing check for potential mixin arguments in at-rule params. 
For example a mixin that adds a fragment with `@media (max-width: value(size))`.

fix: accept mixin argument var used in atrule params

---

packages/webpack-extensions/src/index.ts
packages/webpack-extensions/src/stylable-forcestates-plugin.ts

Component libraries that uses this plugin and apis, used to copy it and change it to allow this functionality. they also made it worse by creating the context for each transformation.
now it's possible to share the context and transform only the selector ast
```ts
const context = createForceStatesContext(dataPrefix, namespaceMapping); // create once
mutateWithForceStates(parseCssSelector('.x:hover'), context); // use in the process
```
* added js docs to public api

feat: added a way to force states on a single selector

---

packages/core/src/stylable-transformer.ts

This PR bails-out fast out of transformation for build-time declaration - any declaration that start with `-st-`.

refactor: bailout transform for internal `-st-` decls

---

packages/language-service/src/lib/css-service.ts
packages/language-service/test/lib/diagnostics.spec.ts

This PR fixes a missed case in [st-scope with no scoping selector](#2883) to make sure that a `@st-scope {}` (no selector) avoids the native css language service ""unknown at-rule" warning

fix: warn diagnostics for `@st-scope` with no selector

---

packages/core/src/stylable-transformer.ts
packages/core/test/features/st-structure.spec.ts

This PR fixes a pseudo-element missed case with the new `@st` structure definition.
When defining a class with pseudo-element and extend, it is expected to resolve the name of the pseudo-element to it's top definition in the inheritance chain:
```css
@st .base {
@st ::part => .part-base;
}
@st .top :is(.base) {
@st ::part => .part-top;
}
/* expect to resolve ::part to ".part-top" */
.top::part {}
```
This doesn't work before this PR because the infer selector process preferred to skip the first resolved symbol (start at `.base` instead of `.top`). This is due to legacy flat mode implicitly defining any local class as a pseudo-element of the `.root` class. Skipping the first resolved symbol allowed targeting both extended parts through pseudo-element syntax or local directly using class …

fix: first level pseudo-element def with extend in structure mode

---

packages/language-service/src/lib/provider.ts
packages/language-service/src/lib/service.ts
packages/language-service/src/lib/utils/wrap-and-log.ts

This PR wraps the main language service APIs, catch and log any unexpected errors, and return a fallback default value.
It should minimize the errors a user sees, and still allow us to research issues.
-----
In addition there is a small fix for `onSignatureHelp` that explodes:
```
.x {
-st-mixin: mix(
arg value(var)^caret:press(ctrl+shift+space)^
)
}
```

fix(lsp): unhandled errors

---

packages/core/src/helpers/custom-state.ts
packages/core/test/features/css-pseudo-class.spec.ts

This PR add a missing error diagnostic when passing an unexpected param to a pseudo-class that doesn't except parameters: template state and boolean state

fix: report unexpected pseudo-state param error

---

package.json
scripts/build.js

Our current runtime output is only compatible with bundlers. When running in Node.js esm modules, we need to use the `.mjs` version of our code, because our package is not currently set to `type: module`.

feat: added a `.mjs` pure runtime to dist

---

packages/webpack-plugin/src/plugin-utils.ts
packages/webpack-plugin/src/plugin.ts

This PR fix a case of false positive `duplicate namespace` error.
There is no test for this case yet, as it is hard to reproduce with our infra, but these are the details:
- `nextjs` in app directory mode
- external stylable lib with 
- components with stylable base 
- component variants that import the base as interface
- user project import (Javascript):
- component _(-> import base stylesheet)_
- variant to style the component _(-> import base stylesheet)_
For some reason, although both imports (component & variant) are resolving the same base stylesheet, `webpack` is generating 2 modules, one with absolute path from the variant and one relative path from the component.
Our `duplicate namespace` check gets both modules, with the same namespace! and report the error.
The fix is to …

fix(webpack): false positive unused stylesheet collision

---

packages/language-service/src/lib-new/edit-time-parser.ts
packages/language-service/test/lib-new/edit-time-parser.spec.ts

Similar to the off-by-one fix in postcss, this PR fixes the offset of invalid nodes.
There is another bug in postcss root source location relating to the column, but we don't use it for anything, so I just left the comment and might create a fix for them at some other time.

fix(lsp): invalid node location offset

---

packages/core/src/features/st-namespace.ts
packages/core/src/stylable-processor.ts
packages/core/test/features/st-namespace.spec.ts
packages/esbuild/test/e2e/duplicate-namespace/a.st.css
packages/esbuild/test/e2e/duplicate-namespace/b.st.css
packages/webpack-plugin/test/e2e/projects/4th-party-project/node_modules/test-components-deep/button.st.css
packages/webpack-plugin/test/e2e/projects/4th-party-project/node_modules/test-components-deep/index.st.css
packages/webpack-plugin/test/e2e/projects/4th-party-project/node_modules/test-components/index.st.css
packages/webpack-plugin/test/e2e/projects/4th-party-project/node_modules/test-components/node_modules/test-components-deep/button.st.css
packages/webpack-plugin/test/e2e/projects/4th-party-project/node_modules/test-components/node_modules/test-components-deep/index.st.css
packages/webpack-plugin/test/e2e/projects/browser-field/node_modules/test-components/cjs/button.st.css
packages/webpack-plugin/test/e2e/projects/browser-field/node_modules/test-components/esm/button.st.css
packages/webpack-plugin/test/e2e/projects/simplest-project-target-node/node_modules/comp-lib/index.cjs.st.css
packages/webpack-plugin/test/e2e/projects/simplest-project-target-node/node_modules/comp-lib/index.es.st.css

This PR adds an info deprecation diagnostics to the native `@namespace` override stylable is doing.
The diagnostic will be reported for the rest of v5 from now on to guide users to change to `@st-namespace` instead and the functionality will be removed in v6.

chore: deprecate native namespace override

---

packages/esbuild/src/plugin-utils.ts
packages/esbuild/src/stylable-esbuild-plugin.ts
packages/esbuild/test/e2e/esbuild-testkit.ts
packages/esbuild/test/e2e/simple-case/a.st.css
packages/esbuild/test/e2e/simple-case/b.st.css
packages/esbuild/test/e2e/simple-case/internal-dir/internal-dir.st.css
packages/esbuild/test/e2e/simple-case/reset.css
packages/esbuild/test/e2e/simple-case/side-effects.st.css
packages/esbuild/test/e2e/simple-case/simple-case.spec.ts

This PR addresses two critical issues that were causing esbuild to fail during the build process when the minify configuration was applied.
Both of these issues arose due to content removal by the minification process, which interfered with the expected behavior of the stylable stylesheet ordering:
1. **Comment-Dependent Sheet Paths**: The first issue stemmed from the reliance on comments injected by esbuild to determine stylesheet paths. These comments were being removed when `minify` was enabled, leading to a runtime-build error.
1. **Start/End Markers Removal**: The second issue pertained to the start and end markers inserted by the stylable plugin. These markers were sometimes eliminated as part of code optimization because they lacked uniqueness.
To resolve these issues, this PR …

fix(esbuild): minify bug

---

packages/core/src/features/st-mixin.ts
packages/core/src/helpers/rule.ts
packages/core/src/stylable-utils.ts
packages/core/test/features/st-mixin.spec.ts
packages/core/test/helpers/rule.spec.ts

This PR fixes some cases of mixins with native CSS nesting:
- mixin with nesting rules
- mix into a nested rule
- preserve nesting selector inside mixed fragment
- error diagnostic in case of a mixin class that is found inside a nested fragment (temporary until we figure out how to handle this case better)
- mix nested at-rule with content
- preserve nesting rules and declaration validity when mixed in an invalid order (nest declarations following nested rules with `&` selector)

fix: mixin with native CSS nesting

---

packages/core/package.json
packages/core/src/module-resolver.ts
packages/core/src/module-with-extensions.ts
packages/create-stylable-app/src/cli-main.ts

rather than defining our own partial polyfill, map it to an empty object and handle `_extensions` not being defined (also safer for future node versions).
also made yargs usage compatible with `"moduleResolution": "bundler"/"node16"`.

refactor(core): module -> {} in browser builds

---

packages/core/src/stylable-transformer.ts
packages/core/test/features/css-pseudo-element.spec.ts

This PR fixes the initial inferred selector for the transform/resolve process for a mapped selector that is created using a `@custom-selector` with the new `experimentalSelectorInference=true` _(only in flat-mode and not the new structure-mode)_.
The difference between the old and new inference is that with the old mode the default context was the `root` of the stylesheet, so any internal custom states/parts were inferred against the root, and that worked fine because only flat structured were allowed, so any custom selector mapping that started with `::part` would refer to a part of the `root`.
With the new `experimentalSelectorInference`, the selector context defaults to `*` (universal selector), making `::part` unknown. So to handle mapping to `::part`, it is assumed that any …

fix: initial mapped-selector infer with experimentalSelectorInference

---

packages/core/src/features/feature.ts
packages/core/src/features/st-scope.ts
packages/core/src/stylable-transformer.ts
packages/core/test/features/st-mixin.spec.ts

This PR fixes an edge case regression that causes a build error. The case involves a combination of mixin as the selector of `@st-scope` with the `experimentalSelectorInference=true` mode.
The difference is that when `experimentalSelectorInference` is on, the transformer doesn't flat `@st-scope` before running, and the alternative `@st-scope` transformation flow doesn't pass the inferred selector mixin value to transform the mixin fragment.
The fix is simply passing along the inferred value to the `@st-scope` transformation process, so it can work in the same way.
This is a quick/dirty fix, but I would like to refactor the entire process to handle all the context and inference values in a cleaner way.

fix: mixin bug with experimentalSelectorInference

---

packages/core/src/features/css-class.ts
packages/core/test/features/css-class.spec.ts
packages/core/test/stylable-transformer/global.spec.ts

This PR makes the `-st-global` mapping from class symbol more strict, disallowing complex selectors and improving the already disallowed multi selector by not transforming it or collecting globals.

feat!: strict class -st-global mapping

---

packages/core/src/helpers/custom-state.ts
packages/core/test/features/css-pseudo-class.spec.ts
packages/schema-extract/test/test.spec.ts

This PR makes sure that custom state templates are simple selectors and disallow:
- complex selector: `.x .y`
- multi-selector: `.x, .y`
- invalid selector: `:unclosed(`
- start with element or universal: `div` / `*`
The same validation already exist for custom state templates with param, but was delayed for the next major version.

feat: validate simple custom state template

---

packages/cli/src/build-stylable.ts
packages/cli/src/config/projects-config.ts
packages/esbuild/src/stylable-esbuild-plugin.ts
packages/rollup-plugin/src/index.ts
packages/webpack-plugin/src/plugin.ts

This PR modifies an internal function argument that was originally intended to be required but was mistakenly set as optional. It is classified as a breaking change because this function is exposed through the `@stylable/cli` index. However, it's worth noting that this function is undocumented and, in all likelihood, not utilized by external parties outside of the project.

refactor(cli)!: make `fs` required in `resolveConfig` function

---

packages/core/src/stylable-resolver.ts

This PR removes the optional `transformer` argument from `resolver.resolveExtends` function.
Passing the transformer argument currently instructs the resolver to first seek a custom selector before inspecting the stylesheet meta for a class and then determining its type accordingly.
There are several reasons for removing this API:
- It is not utilized within Stylable or, to the best of our knowledge, outside of the Stylable repository.
- This functionality relies on custom-selector, which we intend to deprecate in favor of the new structure-mode with mapped selectors, which provides an alternative method for deducing the extended type.
- This is the only workflow that necessitates the presence of the transformer argument in the resolver, complicating our refactoring plans.
In the future, …

chore!: deprecate resolveExtends of custom-selector

---

packages/core/src/features/st-mixin.ts
packages/core/src/features/st-var.ts
packages/core/src/functions.ts
packages/core/src/index-internal.ts
packages/core/src/stylable-resolver.ts
packages/language-service/src/lib/completion-providers.ts
packages/language-service/src/lib/provider.ts
packages/webpack-extensions/src/types.ts

This PR enhances the type definitions for resolved CSS and JS values in the following ways:
1. The CSS resolved type now accurately represents the scenario where the `symbol` field can be `undefined` when the stylesheet exists, but the queried symbol definition is missing.
2. The JS resolved symbol type (exported value) has been updated from the loose `any` type to the more precise `unknown` type.

refactor(types)!: enhance type definitions for resolved CSS and JS values

---

packages/core/src/helpers/rule.ts
packages/core/test/features/st-mixin.spec.ts

This PR resolves a regression where mixins defined within an at-rule, such as `@st-scope`, would inadvertently include extra rules that followed them.
This regression occurred during the [handling of certain native-CSS nested mixin scenarios](https://github.com/wix/stylable/pull/2898).
> this fix will also be backported to version 5.

fix: at-rule mixin collecting extra rules regression

---

packages/cli/src/build-single-file.ts
packages/cli/src/build.ts
packages/core/src/features/st-import.ts
packages/core/src/helpers/import.ts
packages/core/test/features/st-import.spec.ts
packages/esbuild/src/stylable-esbuild-plugin.ts
packages/webpack-plugin/src/loader-utils.ts
packages/webpack-plugin/test/e2e/dual-mode-esm.spec.ts

This PR aligns the depth assignment for stylesheets in CSS-only mode with that of CSS+JS mode.
Previously, prior to this modification, CSS-only mode initiated at a depth level of 0, whereas CSS+JS mode initiated at a depth level of 1. This alteration has been implemented to ensure uniformity and will not impact existing usage. Its primary objective is to facilitate the transition to CSS-only mode as the default setting, thereby minimizing the need for extensive test refactoring.
Additionally, this PR addresses the issue of JS imports for values, formatters, and mixins, preventing them from adding extra depth, as they do not involve CSS overrides.
Furthermore, it prevents a depth increase in the case of circular imports for the stylesheet being calculated, as deeper circular imports are …

fix: align css depth mode to css+js mode

---

package-lock.json
package.json
packages/rollup-plugin/package.json
packages/rollup-plugin/src/index.ts

This PR introduces an upgrade to the tested rollup integration, bumping it up to [version 4](https://github.com/rollup/rollup/releases/tag/v4.0.0), and ensure it works.
During testing, one issue surfaced where [files loaded via the integration's load hook were not automatically watched](https://github.com/rollup/rollup/pull/5150). This update addresses this issue by explicitly adding them to the list of watched files within the integration.
Furthermore, it's worth noting that `rollup@4` installation includes WASM artifacts, which, in some cases, led to failed installation on Windows machines. This problem was resolved by ensuring that Microsoft Visual C++ is installed. The installer for Microsoft Visual C++ can be obtained from this link: https://aka.ms/vs/17/release/vc_redist.x64.exe.

chore: upgrade to support for `rollup@4`

---

packages/core/src/stylable.ts
packages/core/test/stylable-resolver.spec.ts
packages/core/test/stylable-transformer/transformer.unit.spec.ts
packages/esbuild/src/stylable-esbuild-plugin.ts
packages/eslint-plugin-stylable/src/stylable-es-lint.ts
packages/experimental-loader/src/cached-stylable-factory.ts
packages/node/src/loader.ts
packages/node/src/require-hook.ts
packages/rollup-plugin/src/index.ts
packages/webpack-extensions/src/stylable-manifest-plugin.ts

This PR initialize a resolver cache map if one was not provided by the stylable configuration

feat(core)!: default resolver cache

---

packages/core/src/features/st-var.ts
packages/core/src/stylable-transformer.ts
packages/core/test/features/css-custom-property.spec.ts

This PR introduces a deprecation warning for build-vars that reference undefined custom properties in `Stylable@5`.
While the current evaluation mechanism remains unchanged, it will be updated in version 6 (as detailed in the [related PR](https://github.com/wix/stylable/pull/2921)). Users are recommended to either define global custom properties or wrap the value in quotes to achieve the intended result.

chore: deprecation info for unknown custom-properties in build-var

---

packages/core/src/features/css-custom-property.ts
packages/core/src/features/feature.ts
packages/core/src/features/st-mixin.ts
packages/core/src/features/st-var.ts
packages/core/src/functions.ts
packages/core/src/stylable-processor.ts
packages/core/src/stylable-transformer.ts
packages/core/test/features/css-custom-property.spec.ts

This PR modifies the evaluation method for the Stylable build-vars value to ensure its consistency with other values.
Please note, this introduces a breaking change. We had initially deferred this adjustment until version 6. However, to streamline edge cases, we've decided to alter the behavior now.
In the past, the build-var value wasn't assessed in the same manner as other values. This discrepancy led to symbols defined within it being overlooked, especially when referencing a custom property.
For instance, using `buildVar: var(--dynamicVar)` wouldn't define the `--dynamicVar` symbol. As a result, the evaluation of the build-var would retain a global, un-namespaced custom property. Complicating matters, if this property was defined outside the build-var, it would be namespaced. This …

feat(core)!: normalize build-var value

---

packages/runtime/package.json

This pr introduces the addition of `@stylable/runtime/stylesheet` mapping to the exports field in the `package.json` of the runtime package. 
This is specifically aimed at facilitating projects that utilize `TypeScript` with `moduleResolution: node16` in conjunction with the [global stylesheet types approach](https://stylable.io/docs/getting-started/typescript-integration#global-definition).

fix(runtime): expose stylesheet types in package exports

---

packages/core/src/helpers/selector.ts
packages/core/test/features/css-class.spec.ts
packages/core/test/features/st-mixin.spec.ts

This pr fix the code that combines 2 selectors into a single selector in order to fix 2 bugs:
- when nesting a global selector into a `@st-scope`, the   parent selector is ignored
- when mixining a JS mixin, any nested rule that starts with `:global()` is missing the mixed into selector

fix(core): scope nested global selector issues

---

packages/cli/src/build-stylable.ts
packages/cli/src/cli.ts
packages/cli/src/config/resolve-options.ts
packages/cli/src/types.ts
packages/cli/test/cli.spec.ts

This pr fix an issue that caused the `resolveNamespace` cli argument to be overridden in case a `stylable.config ` resolveNamespace is present.
The cli argument `default` is replaced with a `defaultDescription` in order to identify between explicit path and the default path, and the default override order is now done in a single place inside.

fix(cli): resolveNamespace cli arg should override stylable.config

---

packages/cli/src/build-stylable.ts

This pr opens up the `resolveModule` as an argument for  `buildStylable`.
notice that while being part of the cli package, this is not a cli argument, its a programmatic api that is exposed by the cli package.

feat(cli): accept resolveModule in buildStylable

---

packages/core/src/features/css-contains.ts
packages/core/src/features/css-custom-property.ts
packages/core/test/features/css-contains.spec.ts

This PR add basic support for analyzing and transforming custom-properties inside style queries (see [spec](https://drafts.csswg.org/css-contain-3/#container-rule)).
Notice that there is no lsp support atm.

feat(core): container style query

---

packages/core/src/native-reserved-lists.ts
packages/core/test/features/st-structure.spec.ts

This PR add missing native css definitions. 
> Notice that some of them are experimental, but well supported.
**:indeterminate**
- https://drafts.csswg.org/selectors/#indeterminate
**:placeholder-shown**
- https://drafts.csswg.org/selectors/#placeholder
**:user-valid**
- https://drafts.csswg.org/selectors/#user-pseudos
**:autofill**
- https://drafts.csswg.org/selectors/#autofill
**:modal**
- https://drafts.csswg.org/selectors/#modal-state
**:popover-open**
- https://developer.mozilla.org/en-US/docs/Web/CSS/:popover-open
**:future** / **:past**
- https://drafts.csswg.org/selectors/#the-future-pseudo
- https://drafts.csswg.org/selectors/#the-past-pseudo
**:picture-in-picture**
- https://drafts.csswg.org/selectors/#pip-state
**::file-selector-button**
- …

feat(core): add missing native definitions

---

packages/create-stylable-app/template/ts-react-rollup/template.js

This PR add `tslib` as dependency for the rollup template which is required* by the `@rollup/plugin-typescript` when `output.preserveModules = true`.

chore(rollup-template): add required tslib dev dependency

---

packages/core/src/stylable-js-module-source.ts
packages/esbuild/test/e2e/tree-shake/build.js
packages/esbuild/test/e2e/tree-shake/index.html
packages/esbuild/test/e2e/tree-shake/index.js
packages/esbuild/test/e2e/tree-shake/index.st.css
packages/esbuild/test/e2e/tree-shake/stylable.config.js
packages/esbuild/test/e2e/tree-shake/tree-shake.spec.ts
packages/rollup-plugin/test/projects/tree-shake/index.js
packages/rollup-plugin/test/projects/tree-shake/index.st.css
packages/rollup-plugin/test/projects/tree-shake/package.json
packages/rollup-plugin/test/rollup-tree-shake.spec.ts
packages/rollup-plugin/test/test-kit/rollup-runner.ts
packages/webpack-plugin/test/e2e/projects/tree-shake/src/index.js
packages/webpack-plugin/test/e2e/projects/tree-shake/src/index.st.css
packages/webpack-plugin/test/e2e/projects/tree-shake/webpack.config.js
packages/webpack-plugin/test/e2e/tree-shake.spec.ts

This PR removed the /*#__PURE__*/ annotations from the JavaScript module output. The reason for this removal is that these markers appear to trigger errors with `vite@5`:
>A comment "/* #__PURE__*/" in "..." contains an annotation that Rollup cannot interpret due to the position of the comment. The comment will be removed to avoid issues
Although we currently do not conduct tests on vite (at all), this pull request introduces new tests. These tests are designed to verify the effectiveness of tree-shaking for different build tools, including `webpack`, `rollup`, and `esbuild`. The goal is to ensure that the removal of these markers does not adversely impact the final output.
The annotations have been completely removed as it appears they no longer influence tree-shaking. This could be due …

fix(core): remove pure markers from js module output

---

packages/esbuild/src/stylable-esbuild-plugin.ts
packages/esbuild/test/e2e/esbuild-testkit.ts
packages/esbuild/test/e2e/rebuild/rebuild.spec.ts

cherry-pick fix to esbuild from #2938

fix: esbuild plugin break after stylable error (#2938) 5.x

---

packages/core/src/features/st-var.ts
packages/core/test/features/st-var.spec.ts

This PR exposes the source location (meta, start, end) of computed build vars calculated using `stylable.stVar.flatten(meta)` or `stylable.stVar.getComputed(meta)`.

feat: expose computed build vars source location

---

packages/core/src/features/css-custom-property.ts
packages/core/src/features/st-symbol.ts
packages/core/src/stylable.ts
packages/core/test/features/css-custom-property.spec.ts

This PR exposes the available css custom properties available in a stylesheet with their:
- local name in context stylesheet
- local name in definition stylesheet
- transformed name
- source location (meta, start, end)
using the api: `stylable.cssCustomProperty.getProperties(meta)`

feat(core): expose css custom properties api

---

.github/workflows/next.yml
.github/workflows/npm.yml
.github/workflows/publish-tag.yml
.github/workflows/tests.yml

fixes the warnings shown about deprecated action in summary page: https://github.com/wix/stylable/actions/runs/8156888915

ci: upgrade to actions/setup-node@v4

---

packages/core/src/helpers/namespace.ts
packages/core/test/helpers/namespace.spec.ts
packages/node/src/resolve-namespace.ts

When moving files with strict namesapce we didn't clear the cache for the namespace and moving files around caused it to break. in this PR I introduced a devMode to the node resolve namespace Api which checks if the file was deleted when collision happens.

feat: ignore namespace collision of file deleted files

---

packages/core/src/native-reserved-lists.ts

now available in most browsers: https://developer.mozilla.org/en-US/docs/Web/CSS/color_value/light-dark

fix(core): add light-dark() to native fn list

---

packages/code-formatter/src/format-css.ts
packages/code-formatter/test/formatter-experimental.spec.ts

This PR fixes the handling of multi-line declaration values to preserve the original position of comments at the top level of declarations. 
**For example, given the unformatted code:**
```css
.a {
prop:
/*initial comment*/
val1
val2  
}
```
**Before this PR, the comment would be moved to the declaration line:**
```css
.a {
prop: /*initial comment*/
val1
val2  
}
```
**After this PR, the comment remains on its own line:**
```css
.a {
prop:
/*initial comment*/
val1
val2  
}
```

fix(formatter): respect multi-line decl initial comment line

---

packages/code-formatter/src/format-css.ts
packages/code-formatter/test/formatter-experimental.spec.ts

This PR changes the formatter behavior in order to group same name at-rules while maintaining spacing for other at-rule types.
**Before this PR, the following code would remain unchanged:**
```css
@namespace "abc"
@st-import "./a.st.css"
@st-import "./b.st.css"
@property --a;
@property --b;
```
**After this PR, the formatted code will be:**
```css
@namespace "abc"
@st-import "./a.st.css"
@st-import "./b.st.css"
@property --a;
@property --b;
```

feat(formatter): group similar name at-rules

---

packages/build-tools/src/load-stylable-config.ts
packages/create-stylable-app/src/create-project.ts
packages/dom-test-kit/test/tsconfig.json
packages/esbuild/test/e2e/esbuild-testkit.ts
packages/runtime/src/tsconfig.esm.json
packages/uni-driver/test/tsconfig.json
tsconfig.base.json
typings/externals/index.d.ts

added missing project references
worked around vlq having no "types" inside its "exports"

refactor(typescript): use node16 moduleResolution

---

package-lock.json
package.json
scripts/test-runner.js

- adjust test-runner glob to not be wrapped with quotes. these are only needed when running the command directly in the terminal, and wanting the terminal to not try and expand the * itself. it got broken with the new mocha.
- regenerate lock file
https://github.com/mochajs/mocha/releases/tag/v11.1.0

chore(deps-dev): mocha@11.1.0
